"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps, @next/next/no-img-element */

import { useCallback, useEffect, useMemo, useState } from "react";

const LABELS:Record<string,string>={GENERAL:"Квартира",DESIGN:"Дизайн",ESTIMATE:"Смета",ADDITIONAL_WORKS:"Дополнительные работы",PRODUCTION:"Выполненные работы",DAILY_PHOTOS:"Ход работ",HIDDEN_WORKS:"Скрытые работы",FINAL_PHOTOS:"Финальный результат",HANDOVER:"Сдача квартиры",DEFECT_HISTORY:"История замечаний",DOCUMENTS:"Документы",WARRANTY:"Гарантия"};
const PHOTO=new Set(["DAILY_PHOTOS","HIDDEN_WORKS","FINAL_PHOTOS","DEFECT_HISTORY"]);
type History={id:string;number:number;publishedAt:number;releaseNote:string|null;isCurrent:boolean};
type Passport={available:true;passport:{id:string;projectId:string};version:{id:string;number:number;publishedAt:number;releaseNote:string|null;isCurrent:boolean};snapshot:{sections:{key:string;enabled:boolean;position:number}[];general:Record<string,unknown>;design:Record<string,unknown>|null;estimate:Record<string,unknown>|null;additionalWorks:Record<string,unknown>[];commercial:Record<string,unknown>|null;production:{stages:Record<string,unknown>[]};hiddenWorks:Record<string,unknown>[];handover:Record<string,unknown>;defects:Record<string,unknown>[];warranty:Record<string,unknown>;customNote:string|null;coverAttachmentId:string|null};attachmentCounts:Record<string,number>;history:History[]};
type FileItem={id:string;caption:string|null;filename:string;mimeType:string;sizeBytes:number;createdAt:number;url:string};
async function read(path:string){const response=await fetch(path,{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Паспорт недоступен.");return body}
const d=(value:unknown)=>value?new Date(Number(value)*1000).toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"}):"—";
const money=(value:unknown)=>new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0}).format(Number(value||0)/100);
function labelValue(label:string,value:unknown){return <div><span>{label}</span><b>{String(value??"—")}</b></div>}

export function ClientPassport({projectId}:{projectId:string}){
 const[data,setData]=useState<Passport|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");
 const load=useCallback(async(versionId?:string)=>{setBusy(true);setError("");try{setData(await read(`/api/client/passport?projectId=${encodeURIComponent(projectId)}${versionId?`&versionId=${encodeURIComponent(versionId)}`:""}`))}catch(reason){setError(reason instanceof Error?reason.message:"Паспорт недоступен.")}finally{setBusy(false)}},[projectId]);useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>data?.snapshot.sections.filter(item=>item.enabled).sort((a,b)=>a.position-b.position)??[],[data]);
 if(busy&&!data)return <section className="cpp-loading" aria-live="polite"><span/><p>Открываем паспорт квартиры…</p></section>;
 if(!data)return <section className="cp-section"><div className="cp-alert" role="alert">{error}</div><button className="cp-secondary" onClick={()=>load()}>Повторить</button></section>;
 const s=data.snapshot,g=s.general;
 return <article className="cpp" aria-busy={busy}><header className="cpp-cover"><span>DEPA STROY · ПАСПОРТ КВАРТИРЫ</span><h2>{String(g.residentialComplex||g.projectName||"Ваша квартира")}</h2><p>{String(g.address||"")} · кв. {String(g.apartment||"")}</p><div><span>ВЕРСИЯ {data.version.number}</span><b>{d(data.version.publishedAt)}</b></div></header>
  <nav className="cpp-anchors" aria-label="Содержание паспорта">{visible.map(item=><a key={item.key} href={`#passport-${item.key.toLowerCase()}`}>{LABELS[item.key]||item.key}</a>)}</nav>
  {s.customNote?<aside className="cpp-note"><span>ОТ DEPA</span><p>{s.customNote}</p></aside>:null}
  {visible.map(section=><PassportSection key={section.key} sectionKey={section.key} data={data}/>) }
  <section className="cpp-version"><div><span>ВЕРСИИ ПАСПОРТА</span><h3>История обновлений</h3></div><label><span className="sr-only">Версия паспорта</span><select value={data.version.id} disabled={busy} onChange={event=>void load(event.target.value)}>{data.history.map(item=><option value={item.id} key={item.id}>Версия {item.number} · {d(item.publishedAt)}{item.isCurrent?" · текущая":""}</option>)}</select></label>{data.version.releaseNote?<p>{data.version.releaseNote}</p>:null}</section>
 </article>
}

function PassportSection({sectionKey,data}:{sectionKey:string;data:Passport}){const s=data.snapshot,g=s.general;let content:React.ReactNode=null;
 if(sectionKey==="GENERAL")content=<div className="cpp-facts">{labelValue("Жилой комплекс",g.residentialComplex)}{labelValue("Адрес",g.address)}{labelValue("Квартира",g.apartment)}{labelValue("Площадь",g.areaSqm?`${g.areaSqm} м²`:"—")}{labelValue("Клиент",g.clientName)}{labelValue("Фактическая сдача",d(g.actualHandoverAt))}</div>;
 else if(sectionKey==="DESIGN"&&s.design)content=<div className="cpp-facts">{labelValue("Проект",s.design.title)}{labelValue("Статус","Завершён")}{labelValue("Завершён",d(s.design.completedAt))}</div>;
 else if(sectionKey==="ESTIMATE"&&s.estimate){const items=Array.isArray(s.estimate.items)?s.estimate.items as Record<string,unknown>[]:[];content=<><div className="cpp-total"><span>УТВЕРЖДЁННАЯ СТОИМОСТЬ</span><strong>{money(s.estimate.totalKopecks)}</strong></div><div className="cpp-table">{items.map((item,index)=><div key={index}><span>{String(item.section||"")}</span><b>{String(item.name||"")}</b><em>{String(item.quantity||"")} {String(item.unit||"")}</em></div>)}</div></>}
 else if(sectionKey==="ADDITIONAL_WORKS")content=<div className="cpp-list">{s.additionalWorks.map((item,index)=><article key={String(item.id??index)}><div><span>{String(item.number||"ДОПРАБОТА")}</span><b>{String(item.title||"")}</b></div><strong>{money(item.amountKopecks)}</strong></article>)}</div>;
 else if(sectionKey==="PRODUCTION")content=<div className="cpp-list">{s.production.stages.map((item,index)=><article key={String(item.id??index)}><div><span>ВЫПОЛНЕНО</span><b>{String(item.name||"")}</b></div><time>{d(item.actual_end_date)}</time></article>)}</div>;
 else if(sectionKey==="HIDDEN_WORKS")content=<div className="cpp-list">{s.hiddenWorks.map((item,index)=><article key={String(item.requirement_id??index)}><div><span>{String(item.stage||"")}</span><b>{String(item.requirement||"")}</b><small>{String(item.task||"")}</small></div><strong>{String(item.photo_count||0)} фото</strong></article>)}</div>;
 else if(sectionKey==="HANDOVER")content=<div className="cpp-handover"><strong>Квартира принята</strong><p>Фактическая дата сдачи: {d(s.handover.actualHandoverAt||s.handover.acceptedAt)}</p><p>Осмотров: {String(s.handover.roundCount||1)}</p></div>;
 else if(sectionKey==="DEFECT_HISTORY")content=<div className="cpp-list">{s.defects.map((item,index)=><article key={String(item.id??index)}><div><span>ЗАМЕЧАНИЕ №{String(item.defect_number||index+1)}</span><b>{String(item.title||"")}</b><small>{String(item.resolution_comment||"Закрыто при сдаче")}</small></div><em>Закрыто</em></article>)}</div>;
 else if(sectionKey==="WARRANTY")content=<div className="cpp-warranty"><span>ГАРАНТИЯ НА РАБОТЫ</span><strong>Действует с {d(s.warranty.startsAt)}</strong><p>Гарантийные документы доступны в разделе «Документы».</p></div>;
 const count=Number(data.attachmentCounts[sectionKey]||0);return <section className="cpp-section" id={`passport-${sectionKey.toLowerCase()}`}><header><span>{LABELS[sectionKey]||sectionKey}</span><h3>{sectionKey==="GENERAL"?"Ваша квартира":LABELS[sectionKey]||sectionKey}</h3></header>{content}{count?<AttachmentGallery projectId={data.passport.projectId} versionId={data.version.id} sectionKey={sectionKey} photo={PHOTO.has(sectionKey)}/>:content?null:<div className="cpp-empty">В этой версии нет опубликованных материалов.</div>}</section>}

function AttachmentGallery({projectId,versionId,sectionKey,photo}:{projectId:string;versionId:string;sectionKey:string;photo:boolean}){const[items,setItems]=useState<FileItem[]>([]),[cursor,setCursor]=useState<string|null>(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const load=useCallback(async()=>{if(cursor===null||busy)return;setBusy(true);setError("");try{const q=new URLSearchParams({projectId,versionId,sectionKey,limit:"24"});if(cursor)q.set("cursor",cursor);const result=await read(`/api/client/passport/photos?${q}`);setItems(current=>[...current,...result.items]);setCursor(result.nextCursor)}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить файлы.")}finally{setBusy(false)}},[projectId,versionId,sectionKey,cursor,busy]);useEffect(()=>{void load()},[projectId,versionId,sectionKey]);return <div className={photo?"cpp-gallery":"cpp-docs"}>{items.map(item=>photo&&item.mimeType.startsWith("image/")?<a href={item.url} target="_blank" rel="noreferrer" key={item.id}><img src={item.url} loading="lazy" width="640" height="480" alt={item.caption||item.filename}/><span>{item.caption||item.filename}</span></a>:<a href={item.url} target="_blank" rel="noreferrer" key={item.id}><div><span>ДОКУМЕНТ</span><b>{item.caption||item.filename}</b></div><strong>Открыть</strong></a>)}{error?<div className="cp-alert" role="alert">{error}</div>:null}{cursor!==null?<button className="cp-secondary cpp-more" disabled={busy} onClick={()=>void load()}>{busy?"Загружаем…":items.length?"Показать ещё":"Показать материалы"}</button>:null}</div>}
