import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const root=new URL("../",import.meta.url),read=(path)=>readFile(new URL(path,root),"utf8");

test("0014 is additive and never seeds or mutates existing production records",async()=>{const sql=await read("drizzle/postgres/0014_contracts_v1.sql");for(const table of ["contracts","contract_versions","contract_events","company_settings","contract_templates","contract_template_versions"])assert.match(sql,new RegExp(`CREATE TABLE ${table}`));assert.match(sql,/ON DELETE RESTRICT/);assert.doesNotMatch(sql,/DROP TABLE|TRUNCATE|DELETE FROM|UPDATE (users|employees|cashboxes|financial_transactions|leads|clients|orders|inspections|projects|audit_logs)/i);assert.doesNotMatch(sql,/INSERT INTO/i)});
test("contract identities, versions and lifecycle have database constraints",async()=>{const sql=await read("drizzle/postgres/0014_contracts_v1.sql");for(const pattern of [/CREATE SEQUENCE depa_contract_number_seq/,/contracts_number_unique/,/contracts_order_unique/,/contract_versions_number_unique/,/contract_amount_kopecks >= 0/,/DRAFT','READY','SENT','SIGNED','CANCELLED','SUPERSEDED/,/contracts_current_version_fkey/,/contracts_signed_version_fkey/])assert.match(sql,pattern)});
test("Contract creation requires Renovation and an approved estimate, then snapshots all parties",async()=>{const source=await read("lib/contracts.ts");assert.match(source,/o\.type='RENOVATION'/);assert.match(source,/source\.estimate_status !== "APPROVED"/);for(const snapshot of ["client_snapshot_json","company_snapshot_json","property_snapshot_json","terms_snapshot_json","document_snapshot_json"])assert.match(source,new RegExp(snapshot));assert.doesNotMatch(source,/INSERT INTO financial_transactions|UPDATE cashboxes/)});
test("version allocation is transaction serialized and sent or signed versions are immutable",async()=>{const source=await read("lib/contracts.ts");assert.match(source,/pg_advisory_xact_lock/);assert.match(source,/COALESCE\(MAX\(version\),0\)\+1/);assert.match(source,/version\.status!=="DRAFT"/);assert.match(source,/Отправленная или подписанная версия неизменяема/);assert.doesNotMatch(source,/DELETE FROM contract_versions/)});
test("legal readiness is honest when no approved template or company identity exists",async()=>{const [source,ui]=await Promise.all([read("lib/contracts.ts"),read("app/contracts-ui.tsx")]);assert.match(source,/Шаблон договора не заполнен/);assert.match(source,/Заполните обязательные реквизиты компании/);assert.match(ui,/Технический web preview · не юридический документ/);assert.match(ui,/disabled title="Нужен утверждённый шаблон"/)});
test("Contract routes reject unauthenticated calls and expose no DELETE",async()=>{const routes=await Promise.all([read("app/api/contracts/route.ts"),read("app/api/contracts/[id]/route.ts"),read("app/api/company-settings/route.ts")]);for(const route of routes){assert.match(route,/getRequestUser/);assert.match(route,/status:401/);assert.doesNotMatch(route,/export async function DELETE/)}for(const action of ["createVersion","ready","sent","signed","linkSignedFile","cancel","followUp"])assert.match(routes[1],new RegExp(`action==="${action}"`))});
test("contract permissions default closed and include an independent scope",async()=>{const definitions=await read("lib/permission-definitions.ts");for(const permission of ["contracts.view","contracts.create","contracts.edit","contracts.createVersion","contracts.generateDocuments","contracts.markSent","contracts.markSigned","contracts.uploadSigned","contracts.cancel","contracts.viewCompanyDetails","companySettings.view","companySettings.edit","contracts.scope"])assert.match(definitions,new RegExp(permission.replaceAll(".","\\.")));assert.match(definitions,/default: "ASSIGNED"/)});
test("signed contract files use private Blob and exact ContractVersion relation",async()=>{const [files,migration,ui]=await Promise.all([read("lib/files.ts"),read("drizzle/postgres/0014_contracts_v1.sql"),read("app/contracts-ui.tsx")]);for(const category of ["CONTRACT_DOCX","CONTRACT_PDF","SIGNED_CONTRACT","CONTRACT_OTHER"])assert.match(files,new RegExp(category));assert.match(migration,/contract_version_id text/);assert.match(files,/canViewContract/);assert.match(ui,/access:"private"/)});
test("Contracts workspace has required tabs, filters, responsive layout and empty state",async()=>{const [ui,css]=await Promise.all([read("app/contracts-ui.tsx"),read("app/contracts.css")]);for(const label of ["Договоров пока нет","Обзор","Документ","Версии","Файлы","История","Ответственный","Период"])assert.match(ui,new RegExp(label));assert.match(css,/@media\(max-width:700px\)/)});
test("Contracts integrate with Orders, Clients, Projects, CRM and global search",async()=>{const [orders,clients,projects,crm,shell]=await Promise.all([read("app/orders-ui.tsx"),read("lib/clients.ts"),read("lib/projects.ts"),read("lib/contracts.ts"),read("app/depa-os.tsx")]);assert.match(orders,/Договоры/);assert.match(clients,/FROM contracts/);assert.match(projects,/contract_id/);assert.match(crm,/FOLLOW_UP_CONTRACT/);assert.match(shell,/fetch\(`\/api\/contracts\?/)});
