import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const root=new URL("../",import.meta.url),source=path=>readFile(new URL(path,root),"utf8");
const [migration,domain,permissions,employeeRoute,clientRoute,employeeUi,clientUi,files,clientFiles,portal]=await Promise.all([source("drizzle/postgres/0019_final_handover_defects_v1.sql"),source("lib/handovers.ts"),source("lib/permission-definitions.ts"),source("app/api/handovers/[projectId]/route.ts"),source("app/api/client/handover/route.ts"),source("app/handover-ui.tsx"),source("app/client/client-portal-ui.tsx"),source("lib/files.ts"),source("lib/client-files.ts"),source("lib/client-portal.ts")]);
const scenarios=[
 ["01 separate handover",migration,/CREATE TABLE project_handovers/],["02 one per project",migration,/project_handovers_project_unique/],["03 rounds",migration,/CREATE TABLE project_handover_rounds/],["04 one open round",migration,/project_handover_rounds_open_unique/],["05 defects",migration,/CREATE TABLE project_handover_defects/],["06 project defect numbering",migration,/project_handover_defects_number_unique/],["07 handover events",migration,/CREATE TABLE project_handover_events/],["08 defect events",migration,/CREATE TABLE project_handover_defect_events/],["09 checklist foundation",migration,/CREATE TABLE handover_checklist_templates/],["10 round checklist snapshot",migration,/CREATE TABLE project_handover_round_checklist_items/],["11 task link",migration,/CREATE TABLE handover_defect_task_links/],["12 status model",migration,/REINSPECTION_REQUIRED/],["13 defect status model",migration,/DISPUTED/],["14 priority model",migration,/IMPORTANT/],["15 acceptance source",migration,/project_handovers_acceptance_source_check/],["16 resolved comment invariant",migration,/project_handover_defects_resolution_check/],["17 readiness production plan",domain,/NO_PRODUCTION_PLAN/],["18 readiness incomplete stages",domain,/INCOMPLETE_STAGES/],["19 readiness active tasks",domain,/ACTIVE_TASKS/],["20 additional works blocker",domain,/ACTIVE_ADDITIONAL_WORKS/],["21 hidden work warning",domain,/HIDDEN_WORK_PHOTOS/],["22 forecast warning",domain,/NO_PUBLISHED_FORECAST/],["23 finance only warning",domain,/OPEN_OBLIGATIONS/],["24 prepare cannot override",domain,/if \(!readiness\.ready\)/],["25 send active portal",domain,/status='ACTIVE'/],["26 manual reason",domain,/Укажите основание ручной приёмки/],["27 open-defect override",domain,/overrideOpenDefects/],["28 defect advisory lock",domain,/handover-defect:/],["29 round advisory lock",domain,/handover-round:/],["30 final accept row lock",domain,/FOR UPDATE OF h,r/],["31 no financial writes",domain,/final_snapshot_json/],["32 client DTO allowlist",domain,/function clientDto/],["33 central permissions",permissions,/handover\.manualAccept/],["34 assigned scope",permissions,/key: "handover"/],["35 auth employee API",employeeRoute,/Требуется авторизация/],["36 auth client API",clientRoute,/Требуется авторизация клиента/],["37 internal tab",employeeUi,/ФИНАЛЬНАЯ СДАЧА/],["38 client flow",clientUi,/Принять квартиру/],["39 client photos private",clientFiles,/HANDOVER_FILE_UPLOADED/],["40 internal handover files",files,/handover\.uploadFiles/],["41 portal priority",clientUi,/ФИНАЛЬНАЯ СДАЧА/],["42 portal safe summary",portal,/project_handovers/],
];
for(const [name,text,pattern] of scenarios)test(`Final Handover scenario ${name}`,()=>assert.match(text,pattern));
test("migration is additive for business data",()=>assert.doesNotMatch(migration,/\bDROP\s+(?:TABLE|COLUMN)\b|\bTRUNCATE\b|\bDELETE\s+FROM\b/i));
test("handover domain never writes financial state",()=>assert.doesNotMatch(domain,/INSERT INTO (?:financial_transactions|obligations)|UPDATE cashboxes/i));
test("client DTO excludes internal assignment and comments",()=>{const dto=domain.slice(domain.indexOf("function clientDto"),domain.indexOf("export async function getClientProjectHandover"));assert.doesNotMatch(dto,/internal_comment|assigned_to_user_id|metadata_json/)});
test("handover UI has no prompt",()=>{assert.doesNotMatch(employeeUi,/window\.prompt|\bprompt\(/);assert.doesNotMatch(clientUi,/window\.prompt|\bprompt\(/)});
