import { getRequestUser } from "../../../../lib/auth";
import { createTemplate,listTemplates,mutateTemplate,ProductionError,type ProductionInput } from "../../../../lib/production";
import { AccessError } from "../../../../lib/permissions";
import { createRequestLogger } from "../../../../lib/request-logger";
export const dynamic="force-dynamic";
function fail(error:unknown){if(error instanceof ProductionError||error instanceof AccessError)return Response.json({error:error.message},{status:error.status});return Response.json({error:"Не удалось выполнить операцию с шаблоном."},{status:500})}
export async function GET(request:Request){const actor=await getRequestUser(request);if(!actor)return Response.json({error:"Требуется авторизация."},{status:401});try{return Response.json(await listTemplates(actor),{headers:{"Cache-Control":"private, no-store"}})}catch(error){return fail(error)}}
export async function POST(request:Request){const actor=await getRequestUser(request),log=createRequestLogger(request,{route:"/api/production/templates",action:"PRODUCTION_TEMPLATE_CREATE",actorType:actor?"EMPLOYEE":"ANONYMOUS",actorId:actor?.id??null});if(!actor){log.failure("PRODUCTION_TEMPLATE_CREATE_FAILURE",new Error("Unauthorized"),{errorCode:"UNAUTHORIZED"});return log.json({error:"Требуется авторизация."},{status:401})}let body:ProductionInput={};try{body=await request.json() as ProductionInput;const result=await createTemplate(actor,body);log.success("PRODUCTION_TEMPLATE_CREATE_SUCCESS",{entityId:"id" in result?String(result.id):null});return log.json(result,{status:201})}catch(error){log.failure("PRODUCTION_TEMPLATE_CREATE_FAILURE",error,{errorCode:error instanceof ProductionError||error instanceof AccessError?`PRODUCTION_TEMPLATE_${error.status}`:"PRODUCTION_TEMPLATE_INTERNAL"});return log.withRequestId(fail(error))}}
export async function PATCH(request:Request){const actor=await getRequestUser(request),log=createRequestLogger(request,{route:"/api/production/templates",action:"PRODUCTION_TEMPLATE_MUTATION",actorType:actor?"EMPLOYEE":"ANONYMOUS",actorId:actor?.id??null});if(!actor){log.failure("PRODUCTION_TEMPLATE_MUTATION_FAILURE",new Error("Unauthorized"),{errorCode:"UNAUTHORIZED"});return log.json({error:"Требуется авторизация."},{status:401})}let body:ProductionInput={};try{body=await request.json() as ProductionInput;const result=await mutateTemplate(actor,body);log.success("PRODUCTION_TEMPLATE_MUTATION_SUCCESS",{entityId:String(body.templateId??"")||null,templateAction:body.action});return log.json(result)}catch(error){log.failure("PRODUCTION_TEMPLATE_MUTATION_FAILURE",error,{entityId:typeof body!=="undefined"?String(body.templateId??"")||null:null,errorCode:error instanceof ProductionError||error instanceof AccessError?`PRODUCTION_TEMPLATE_${error.status}`:"PRODUCTION_TEMPLATE_INTERNAL"});return log.withRequestId(fail(error))}}
