"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useCallback, useEffect, useMemo, useState } from "react";

const SECTION_LABELS:Record<string,string>={GENERAL:"Общие сведения",DESIGN:"Дизайн-проект",ESTIMATE:"Утверждённая смета",ADDITIONAL_WORKS:"Дополнительные работы",PRODUCTION:"Выполненные этапы",DAILY_PHOTOS:"Фото хода работ",HIDDEN_WORKS:"Скрытые работы",FINAL_PHOTOS:"Финальные фотографии",HANDOVER:"Финальная сдача",DEFECT_HISTORY:"История замечаний",DOCUMENTS:"Документы",WARRANTY:"Гарантия"};
const MANDATORY=new Set(["GENERAL","HANDOVER"]);
type Section={section_key:string;enabled:number;position:number};
type SourceFile={id:string;section_key:string;original_filename:string;mime_type:string;size_bytes:number};
type PassportData={passport:{id:string;status:string;cover_attachment_id:string|null;custom_note:string|null;financial_summary_enabled:number;excluded_attachment_ids_json:string[];attachment_captions_json:Record<string,string>;archive_reason?:string|null};sections:Section[];readiness:{ready:boolean;blockers:{code:string;message:string}[];warnings:{code:string;message:string}[];completeness:{available:number;applicable:number};selected:SourceFile[];sourceFiles:SourceFile[];counts:{sections:number;photos:number;documents:number;hiddenWorks:number};snapshot:Record<string,unknown>};versions:{id:string;version_number:number;release_note:string|null;published_at:number}[];events:{type:string;comment:string|null;occurred_at:number}[];capabilities:{preview:boolean;manage:boolean;publish:boolean;archive:boolean}};
async function request(projectId:string,init?:RequestInit){const response=await fetch(`/api/apartment-passports/${projectId}`,{cache:"no-store",...init});const body=await response.json();if(!response.ok)throw new Error(body.error||"Не удалось выполнить действие.");return body as PassportData}
const date=(seconds:number)=>new Date(seconds*1000).toLocaleString("ru-RU");
const size=(bytes:number)=>bytes>1024*1024?`${(bytes/1024/1024).toFixed(1)} МБ`:`${Math.max(1,Math.round(bytes/1024))} КБ`;

export function ApartmentPassportPanel({projectId}:{projectId:string}){
 const[data,setData]=useState<PassportData|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(""),[saved,setSaved]=useState(false),[releaseNote,setReleaseNote]=useState(""),[archiveReason,setArchiveReason]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{setData(await request(projectId))}catch(reason){setError(reason instanceof Error?reason.message:"Паспорт недоступен.")}finally{setBusy(false)}},[projectId]);useEffect(()=>{void load()},[load]);
 const mutate=useCallback(async(body:Record<string,unknown>)=>{setBusy(true);setError("");setSaved(false);try{setData(await request(projectId,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}));setSaved(true)}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось сохранить изменения.")}finally{setBusy(false)}},[projectId]);
 const enabled=useMemo(()=>new Set(data?.sections.filter(item=>Number(item.enabled)===1).map(item=>item.section_key)??[]),[data]);
 function saveSections(nextSections= data?.sections??[]){if(!data)return;void mutate({action:"SETTINGS",sections:nextSections.map(item=>({key:item.section_key,enabled:Number(item.enabled)===1})),coverAttachmentId:data.passport.cover_attachment_id,customNote:data.passport.custom_note,financialSummaryEnabled:Boolean(Number(data.passport.financial_summary_enabled)),excludedAttachmentIds:data.passport.excluded_attachment_ids_json,attachmentCaptions:data.passport.attachment_captions_json})}
 if(busy&&!data)return <section className="passport-panel passport-loading" aria-live="polite">Формируем черновик паспорта…</section>;
 if(!data)return <section className="passport-panel"><div className="passport-alert" role="alert">{error}</div><button className="secondary" onClick={load}>Повторить</button></section>;
 const p=data.passport,r=data.readiness,excluded=new Set(p.excluded_attachment_ids_json??[]),files=r.sourceFiles;
 return <div className="passport-panel">
  <header className="passport-title"><div><span className="eyebrow">ПАСПОРТ КВАРТИРЫ</span><h3>Цифровой архив объекта</h3><p>Паспорт собирает только существующие клиентские данные и файлы. Публикация создаёт неизменяемую версию.</p></div><span className={`passport-status ${p.status.toLowerCase()}`}>{p.status==="PUBLISHED"?"Опубликован":p.status==="ARCHIVED"?"В архиве":r.ready?"Готов к публикации":"Черновик"}</span></header>
  {error?<div className="passport-alert" role="alert">{error}</div>:null}{saved?<div className="passport-success" role="status">Изменения сохранены.</div>:null}
  <section className="passport-readiness"><div><strong>{r.completeness.available} / {r.completeness.applicable}</strong><span>источников доступны</span></div><div><strong>{r.counts.photos}</strong><span>фотографий</span></div><div><strong>{r.counts.documents}</strong><span>документов</span></div><div><strong>{data.versions.length}</strong><span>версий</span></div></section>
  {r.blockers.length?<section className="passport-blockers"><h4>До публикации</h4>{r.blockers.map(item=><p key={item.code}>{item.message}</p>)}</section>:null}
  <div className="passport-layout"><section className="passport-editor"><div className="passport-section-head"><div><span className="eyebrow">СОСТАВ</span><h4>Разделы паспорта</h4></div><small>Общие сведения и сдача обязательны</small></div><div className="passport-section-list">{data.sections.map((section,index)=><label key={section.section_key}><input type="checkbox" checked={enabled.has(section.section_key)} disabled={!data.capabilities.manage||MANDATORY.has(section.section_key)||busy} onChange={event=>{const next=data.sections.map((item,i)=>i===index?{...item,enabled:event.target.checked?1:0}:item);setData({...data,sections:next});saveSections(next)}}/><span><b>{SECTION_LABELS[section.section_key]??section.section_key}</b><small>{MANDATORY.has(section.section_key)?"Обязательный раздел":r.warnings.some(item=>item.code===`${section.section_key}_MISSING`)?"Пока нет данных":"Источник найден"}</small></span></label>)}</div>
   <label className="passport-field"><span>Комментарий для клиента</span><textarea value={p.custom_note??""} disabled={!data.capabilities.manage} maxLength={1000} onChange={event=>setData({...data,passport:{...p,custom_note:event.target.value}})} placeholder="Необязательное пояснение к паспорту"/></label>
   <label className="passport-check"><input type="checkbox" checked={Boolean(Number(p.financial_summary_enabled))} disabled={!data.capabilities.manage} onChange={event=>setData({...data,passport:{...p,financial_summary_enabled:event.target.checked?1:0}})}/><span><b>Показать коммерческую сводку</b><small>Только согласованные клиентские суммы, без себестоимости и маржи.</small></span></label>
   {data.capabilities.manage?<button className="secondary" disabled={busy} onClick={()=>saveSections()}>Сохранить настройки</button>:null}
  </section>
  <section className="passport-preview"><div className="passport-section-head"><div><span className="eyebrow">ПРЕДПРОСМОТР</span><h4>Файлы будущей версии</h4></div><small>{files.length} шт.</small></div>{files.length?<div className="passport-file-list">{files.map(file=><article key={file.id}><label><input type="checkbox" checked={!excluded.has(file.id)} disabled={!data.capabilities.manage} onChange={event=>{const next=new Set(p.excluded_attachment_ids_json??[]);if(event.target.checked)next.delete(file.id);else next.add(file.id);setData({...data,passport:{...p,cover_attachment_id:!event.target.checked&&p.cover_attachment_id===file.id?null:p.cover_attachment_id,excluded_attachment_ids_json:[...next]}})}}/><span><b>{file.original_filename}</b><small>{SECTION_LABELS[file.section_key]} · {size(Number(file.size_bytes))}</small></span></label><input aria-label={`Подпись к ${file.original_filename}`} value={p.attachment_captions_json?.[file.id]??""} disabled={!data.capabilities.manage} maxLength={300} placeholder="Подпись для клиента" onChange={event=>setData({...data,passport:{...p,attachment_captions_json:{...p.attachment_captions_json,[file.id]:event.target.value}}})}/><button type="button" className={p.cover_attachment_id===file.id?"selected":""} disabled={!data.capabilities.manage||!["FINAL_PHOTOS","DAILY_PHOTOS"].includes(file.section_key)||excluded.has(file.id)} onClick={()=>setData({...data,passport:{...p,cover_attachment_id:p.cover_attachment_id===file.id?null:file.id}})}>{p.cover_attachment_id===file.id?"Обложка выбрана":"На обложку"}</button></article>)}</div>:<div className="passport-empty">Клиентские файлы появятся здесь автоматически после загрузки в существующие модули.</div>}</section></div>
  <section className="passport-publish"><div><span className="eyebrow">ПУБЛИКАЦИЯ</span><h4>{data.versions.length?"Создать новую версию":"Опубликовать первую версию"}</h4><p>После публикации содержание версии и её ссылки на файлы нельзя изменить.</p></div><label><span>Что изменилось</span><input value={releaseNote} maxLength={500} onChange={event=>setReleaseNote(event.target.value)} placeholder="Например: добавлены гарантийные документы"/></label><button className="primary" disabled={busy||!r.ready||!data.capabilities.publish||p.status==="ARCHIVED"} onClick={()=>{if(window.confirm("Опубликовать неизменяемую версию паспорта для клиента?"))void mutate({action:"PUBLISH",releaseNote})}}>{busy?"Публикуем…":data.versions.length?"Опубликовать новую версию":"Опубликовать паспорт"}</button></section>
  {data.versions.length?<section className="passport-history"><div className="passport-section-head"><div><span className="eyebrow">ИСТОРИЯ</span><h4>Опубликованные версии</h4></div></div>{data.versions.map(version=><article key={version.id}><strong>v{version.version_number}</strong><span>{version.release_note||"Первая публикация"}</span><time>{date(Number(version.published_at))}</time></article>)}</section>:null}
  {data.capabilities.archive?<footer className="passport-danger">{p.status==="ARCHIVED"?<button className="secondary" disabled={busy} onClick={()=>void mutate({action:"RESTORE"})}>Восстановить паспорт</button>:<><label><span>Причина архивации</span><input value={archiveReason} maxLength={1000} onChange={event=>setArchiveReason(event.target.value)} placeholder="Обязательное основание"/></label><button className="secondary danger" disabled={busy||!archiveReason.trim()} onClick={()=>{if(window.confirm("Архивировать паспорт? Опубликованные версии сохранятся."))void mutate({action:"ARCHIVE",reason:archiveReason})}}>Архивировать паспорт</button></>}</footer>:null}
 </div>
}
