"use client";

import { useEffect, useRef, useState } from "react";
import type { AuthUser } from "../lib/auth";
import type { AccessProfile } from "../lib/permission-definitions";

type Complex = { id: string; name: string; city: string; address: string; developer: string | null; district: string | null; comment: string | null; status: "ACTIVE" | "ARCHIVED"; createdAt: number; updatedAt: number; archivedAt: number | null; creatorName: string; counts: { inspections: number; designs: number; projects: number } };
type Result = { items: Complex[]; total: number; nextOffset: number | null; cities: string[] };

async function json<T>(response: Response) { const result = await response.json() as T & { error?: string }; if (!response.ok) throw Object.assign(new Error(result.error || "Операция не выполнена."), result); return result; }
function date(value: number) { return new Date(value * 1000).toLocaleString("ru-RU", { dateStyle: "medium", timeStyle: "short" }); }

function ComplexForm({ item, onClose, onSaved }: { item?: Complex; onClose: () => void; onSaved: (item: Complex) => void }) {
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [duplicate, setDuplicate] = useState<Complex | null>(null); const formRef = useRef<HTMLFormElement>(null);
  async function save(allowDuplicate = false) { if (!formRef.current) return; setBusy(true); setError(""); setDuplicate(null); try { const payload = { ...Object.fromEntries(new FormData(formRef.current)), allowDuplicate }; const saved = await json<Complex>(await fetch(item ? `/api/residential-complexes/${item.id}` : "/api/residential-complexes", { method: item ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) })); onSaved(saved); } catch (reason) { const failure = reason as Error & { code?: string; duplicates?: Complex[] }; if (failure.code === "POSSIBLE_DUPLICATE" && failure.duplicates?.length) setDuplicate(failure.duplicates[0]); else setError(failure.message); } finally { setBusy(false); } }
  return <div className="modal-wrap rc-drawer-wrap" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside className="rc-drawer"><header><div><span className="eyebrow">СПРАВОЧНИК ЖК</span><h3>{item ? "Редактировать ЖК" : "Добавить ЖК"}</h3></div><button aria-label="Закрыть" onClick={onClose}>×</button></header><form ref={formRef} onSubmit={(event) => { event.preventDefault(); void save(); }}>
    <label><span>Название *</span><input name="name" defaultValue={item?.name} required autoFocus /></label><label><span>Город *</span><input name="city" defaultValue={item?.city} required /></label><label className="wide"><span>Адрес *</span><input name="address" defaultValue={item?.address} required /></label><label><span>Застройщик</span><input name="developer" defaultValue={item?.developer || ""} /></label><label><span>Район</span><input name="district" defaultValue={item?.district || ""} /></label><label className="wide"><span>Комментарий</span><textarea name="comment" defaultValue={item?.comment || ""} rows={5} /></label>
    {duplicate ? <div className="duplicate-warning wide"><b>Возможный дубль: {duplicate.name}</b><span>{duplicate.city} · {duplicate.address}</span><small>Проверьте карточку перед принудительным сохранением.</small></div> : null}{error ? <div className="form-error wide">{error}</div> : null}<footer className="wide"><button type="button" className="secondary" onClick={onClose}>Отмена</button>{duplicate ? <button type="button" className="secondary" disabled={busy} onClick={() => void save(true)}>Всё равно сохранить</button> : null}<button className="primary" disabled={busy}>{busy ? "Сохраняем…" : "Сохранить"}</button></footer>
  </form></aside></div>;
}

function ComplexCard({ item, access, onClose, onChanged, onEdit }: { item: Complex; access: AccessProfile; onClose: () => void; onChanged: (item: Complex) => void; onEdit: () => void }) {
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function archive() { const nextArchived = item.status === "ACTIVE"; if (!window.confirm(nextArchived ? "Архивировать ЖК? Существующие связи сохранятся." : "Восстановить ЖК?")) return; setBusy(true); try { onChanged(await json<Complex>(await fetch(`/api/residential-complexes/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: nextArchived ? "ARCHIVE" : "RESTORE" }) }))); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось изменить статус."); } finally { setBusy(false); } }
  return <div className="modal-wrap rc-card-wrap" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside className="rc-card"><header><button className="back" onClick={onClose}>← Все ЖК</button><div><span className={`rc-status ${item.status.toLowerCase()}`}>{item.status === "ACTIVE" ? "Активный" : "Архивный"}</span><h2>{item.name}</h2><p>{item.city} · {item.address}</p></div><div>{access.actions["residentialComplexes.edit"] ? <button className="primary" onClick={onEdit}>Редактировать</button> : null}<button aria-label="Закрыть" onClick={onClose}>×</button></div></header>{error ? <div className="form-error">{error}</div> : null}<section className="rc-card-body"><div className="panel rc-facts">{[["Застройщик", item.developer || "—"], ["Район", item.district || "—"], ["Создал", item.creatorName], ["Обновлён", date(item.updatedAt)]].map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</div><div className="rc-counts"><article className="panel"><span>Приёмки</span><b>{item.counts.inspections}</b></article><article className="panel"><span>Дизайн-проекты</span><b>{item.counts.designs}</b></article><article className="panel"><span>Объекты</span><b>{item.counts.projects}</b></article></div><section className="panel rc-comment"><span className="eyebrow">КОММЕНТАРИЙ</span><p>{item.comment || "Комментарий пока не добавлен."}</p></section>{access.actions["residentialComplexes.archive"] ? <button className="link danger-text" disabled={busy} onClick={() => void archive()}>{item.status === "ACTIVE" ? "Архивировать ЖК" : "Восстановить ЖК"}</button> : null}</section></aside></div>;
}

export function ResidentialComplexesScreen({ currentUser, access, initialId = null, onClosed }: { currentUser: AuthUser; access: AccessProfile; initialId?: string | null; onClosed?: () => void }) {
  const [items, setItems] = useState<Complex[]>([]); const [cities, setCities] = useState<string[]>([]); const [total, setTotal] = useState(0); const [nextOffset, setNextOffset] = useState<number | null>(null); const [search, setSearch] = useState(""); const [status, setStatus] = useState("ACTIVE"); const [city, setCity] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [revision, setRevision] = useState(0); const [selected, setSelected] = useState<Complex | null>(null); const [form, setForm] = useState<Complex | "new" | null>(null);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => { setLoading(true); const params = new URLSearchParams({ search, status, city, limit: "30", offset: "0" }); fetch(`/api/residential-complexes?${params}`, { cache: "no-store", signal: controller.signal }).then((response) => json<Result>(response)).then((result) => { setItems(result.items); setCities(result.cities); setTotal(result.total); setNextOffset(result.nextOffset); if (initialId && !selected) { const found = result.items.find((item) => item.id === initialId); if (found) setSelected(found); else fetch(`/api/residential-complexes/${initialId}`, { cache: "no-store" }).then((response) => json<Complex>(response)).then(setSelected).catch(() => undefined); } setError(""); }).catch((reason) => { if (reason?.name !== "AbortError") setError(reason instanceof Error ? reason.message : "Не удалось загрузить справочник."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); }, 220); return () => { window.clearTimeout(timer); controller.abort(); }; }, [search, status, city, revision, initialId, selected]);
  async function more() { if (nextOffset == null) return; const params = new URLSearchParams({ search, status, city, limit: "30", offset: String(nextOffset) }); try { const result = await json<Result>(await fetch(`/api/residential-complexes?${params}`, { cache: "no-store" })); setItems((current) => [...current, ...result.items]); setNextOffset(result.nextOffset); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось загрузить ЖК."); } }
  function changed(item: Complex) { setSelected(item); setForm(null); setRevision((value) => value + 1); }
  const canCreate = currentUser.role === "OWNER" || Boolean(access.actions["residentialComplexes.create"]);
  return <section className="screen-section rc-screen"><div className="screen-intro"><div><span className="eyebrow">ЕДИНЫЙ СПРАВОЧНИК</span><h2>Жилые комплексы</h2><p>Один источник данных для приёмок, дизайн-проектов и ремонтных объектов.</p></div>{canCreate ? <button className="primary" onClick={() => setForm("new")}>＋ Добавить ЖК</button> : null}</div><div className="panel rc-list-panel"><div className="rc-filters"><label className="rc-search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Название, адрес или застройщик" /></label><label><span>Статус</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="ACTIVE">Активные</option><option value="ARCHIVED">Архивные</option><option value="ALL">Все</option></select></label><label><span>Город</span><select value={city} onChange={(event) => setCity(event.target.value)}><option value="">Все города</option>{cities.map((value) => <option value={value} key={value}>{value}</option>)}</select></label></div><div className="rc-list-meta"><span>Найдено: {total}</span><small>Удаление запрещено · архив сохраняет связи</small></div>{error ? <div className="form-error">{error}</div> : null}{!loading && !items.length ? <div className="rc-empty"><span>◇</span><h3>ЖК пока нет.</h3><p>{search || city || status !== "ACTIVE" ? "Измените поиск или фильтры." : "Добавьте первый жилой комплекс в общий справочник."}</p>{canCreate && !search && !city && status === "ACTIVE" ? <button className="primary" onClick={() => setForm("new")}>Добавить ЖК</button> : null}</div> : <div className="rc-table"><div className="rc-row head"><span>ЖК</span><span>Город</span><span>Застройщик</span><span>Связи</span><span>Статус</span></div>{items.map((item) => <button className="rc-row" key={item.id} onClick={() => setSelected(item)}><span><b>{item.name}</b><small>{item.address}</small></span><span>{item.city}</span><span>{item.developer || "—"}</span><span>{item.counts.inspections} / {item.counts.designs} / {item.counts.projects}</span><span><em className={`rc-status ${item.status.toLowerCase()}`}>{item.status === "ACTIVE" ? "Активный" : "Архивный"}</em></span></button>)}</div>}{loading ? <div className="finance-loading">Загружаем ЖК…</div> : null}{nextOffset != null ? <button className="secondary rc-more" onClick={() => void more()}>Показать ещё</button> : null}</div>
    {selected ? <ComplexCard item={selected} access={access} onClose={() => { setSelected(null); onClosed?.(); }} onChanged={changed} onEdit={() => setForm(selected)} /> : null}{form ? <ComplexForm item={form === "new" ? undefined : form} onClose={() => setForm(null)} onSaved={changed} /> : null}
  </section>;
}
