import { head, type PutBlobResult } from "@vercel/blob";
import type { ClientPortalUser } from "./client-portal";
import { ClientPortalError } from "./client-portal";
import { attachmentPath, DOCUMENT_MAX_BYTES } from "./files";
import { first, query, transaction } from "./postgres";

const PROOF_MIMES=["image/jpeg","image/png","image/webp","image/heic","image/heif","application/pdf"];
const now=()=>Math.floor(Date.now()/1000);
const clean=(value:unknown,max:number)=>typeof value==="string"?value.trim().replace(/[\u0000-\u001f\u007f]/g,"").slice(0,max):"";

export async function prepareClientPaymentProofUpload(user:ClientPortalUser,pathname:string,clientPayload:string|null){
  let raw:Record<string,unknown>;try{raw=JSON.parse(clientPayload??"null") as Record<string,unknown>}catch{throw new ClientPortalError("Некорректные параметры загрузки.")}
  const attachmentId=clean(raw?.attachmentId,100),claimId=clean(raw?.claimId,100),filename=clean(raw?.originalFilename,240),mime=clean(raw?.mimeType,100).toLowerCase(),size=Number(raw?.sizeBytes);
  if(!attachmentId||!claimId||!filename||!PROOF_MIMES.includes(mime)||!Number.isInteger(size)||size<=0||size>DOCUMENT_MAX_BYTES)throw new ClientPortalError("Файл не прошёл проверку типа или размера.");
  const claim=await first<{project_id:string;responsible_user_id:string}>("SELECT pc.project_id,p.responsible_user_id FROM client_payment_claims pc JOIN projects p ON p.id=pc.project_id WHERE pc.id=$1 AND pc.client_id=$2 AND pc.portal_user_id=$3 AND pc.status='PENDING'",[claimId,user.clientId,user.id]);
  if(!claim)throw new ClientPortalError("Заявление об оплате недоступно.",403);
  const expected=attachmentPath(attachmentId,"OTHER",mime);if(pathname!==expected)throw new ClientPortalError("Путь загрузки отклонён.");const timestamp=now();
  await query(`INSERT INTO attachments(id,project_id,client_payment_claim_id,client_visible,storage_provider,storage_key,original_filename,mime_type,size_bytes,uploaded_by_user_id,entity_type,entity_id,category,visibility,upload_status,metadata_json,created_at,updated_at)
    VALUES($1,$2,$3,1,'VERCEL_BLOB',$4,$5,$6,0,$7,'ClientPaymentClaim',$3,'OTHER','CLIENT','PENDING',$8::jsonb,$9,$9)`,[attachmentId,claim.project_id,claimId,expected,filename,mime,claim.responsible_user_id,JSON.stringify({declaredSizeBytes:size,uploadedByClientPortalUserId:user.id}),timestamp]);
  return{allowedContentTypes:PROOF_MIMES,maximumSizeInBytes:DOCUMENT_MAX_BYTES,validUntil:Date.now()+10*60*1000,addRandomSuffix:false,allowOverwrite:false,cacheControlMaxAge:60,tokenPayload:JSON.stringify({attachmentId,portalUserId:user.id,clientId:user.clientId})};
}

export async function finalizeClientPaymentProofUpload(blob:PutBlobResult,tokenPayload:string|null|undefined){let signed:{attachmentId?:string;portalUserId?:string;clientId?:string};try{signed=JSON.parse(tokenPayload??"null") as typeof signed}catch{throw new ClientPortalError("Некорректное подтверждение загрузки.")}if(!signed?.attachmentId||!signed.portalUserId||!signed.clientId)throw new ClientPortalError("Некорректное подтверждение загрузки.");const row=await first<{id:string;storage_key:string;mime_type:string;client_payment_claim_id:string;metadata_json:Record<string,unknown>}>("SELECT id,storage_key,mime_type,client_payment_claim_id,metadata_json FROM attachments WHERE id=$1 AND upload_status='PENDING'",[signed.attachmentId]);if(!row||row.storage_key!==blob.pathname||row.metadata_json?.uploadedByClientPortalUserId!==signed.portalUserId||!blob.url.includes(".private.blob.vercel-storage.com/"))throw new ClientPortalError("Загрузка не найдена.",404);const metadata=await head(row.storage_key),size=Number(metadata.size),mime=clean(blob.contentType||row.mime_type,100).toLowerCase();if(!PROOF_MIMES.includes(mime)||size<=0||size>DOCUMENT_MAX_BYTES)throw new ClientPortalError("Файл не прошёл проверку.");const timestamp=now();await transaction([{text:"UPDATE attachments SET blob_url=$1,mime_type=$2,size_bytes=$3,upload_status='LINKED',completed_at=$4,linked_at=$4,updated_at=$4 WHERE id=$5 AND upload_status='PENDING'",params:[blob.url,mime,size,timestamp,row.id]},{text:"INSERT INTO client_portal_audit_events(id,action,entity_type,entity_id,client_id,client_portal_user_id,metadata_json,occurred_at) VALUES($1,'CLIENT_PAYMENT_PROOF_UPLOADED','Attachment',$2,$3,$4,$5::jsonb,$6)",params:[crypto.randomUUID(),row.id,signed.clientId,signed.portalUserId,JSON.stringify({claimId:row.client_payment_claim_id,mimeType:mime,sizeBytes:size}),timestamp]}]);}

export async function getClientAuthorizedAttachment(user:ClientPortalUser,attachmentId:string){const row=await first<Record<string,unknown>>(`SELECT a.* FROM attachments a LEFT JOIN projects p ON p.id=a.project_id LEFT JOIN client_payment_claims pc ON pc.id=a.client_payment_claim_id WHERE a.id=$1 AND a.upload_status='LINKED' AND a.deleted_at IS NULL AND ((a.project_id IS NOT NULL AND p.client_id=$2 AND (a.client_visible=1 OR a.visibility='CLIENT')) OR (a.client_payment_claim_id IS NOT NULL AND pc.client_id=$2)) LIMIT 1`,[attachmentId,user.clientId]);if(!row)throw new ClientPortalError("Файл недоступен.",403);return row as {id:string;storage_key:string;original_filename:string;mime_type:string;size_bytes:number};}

export async function auditClientFileViewed(user:ClientPortalUser,attachmentId:string){await query("INSERT INTO client_portal_audit_events(id,action,entity_type,entity_id,client_id,client_portal_user_id,metadata_json,occurred_at) VALUES($1,'CLIENT_FILE_VIEWED','Attachment',$2,$3,$4,'{}',$5)",[crypto.randomUUID(),attachmentId,user.clientId,user.id,now()]);}
