import type { AuthUser } from "./auth";
import { confirmAttachmentUpload } from "./files";
import { first, query, transaction } from "./postgres";
import { AccessError, assertModuleAction, getAccessProfile } from "./permissions";

export type ContractInput = Record<string, unknown>;
type ContractAction = "contracts.view" | "contracts.create" | "contracts.edit" | "contracts.createVersion" | "contracts.generateDocuments" | "contracts.markSent" | "contracts.markSigned" | "contracts.uploadSigned" | "contracts.cancel" | "contracts.viewCompanyDetails" | "companySettings.view" | "companySettings.edit";
type ContractStatus = "DRAFT" | "READY" | "SENT" | "SIGNED" | "CANCELLED" | "SUPERSEDED";

export class ContractError extends Error {
  constructor(message: string, public status = 400, public details?: Record<string, unknown>) { super(message); }
}

const now = () => Math.floor(Date.now() / 1000);
const clean = (value: unknown, max = 2000) => typeof value === "string" ? value.trim().replace(/[\u0000-\u001f\u007f]/g, "").slice(0, max) || null : null;
const id = (value: unknown) => clean(value, 120);
const integer = (value: unknown, nullable = true) => {
  if (value === null || value === undefined || value === "") return nullable ? null : 0;
  const result = typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value) ? Math.floor(new Date(`${value}T00:00:00+10:00`).getTime()/1000) : Number(value);
  if (!Number.isSafeInteger(result) || result < 0) throw new ContractError("Проверьте числовые значения договора."); return result;
};
const json = (value: unknown) => JSON.stringify(value ?? {});

function audit(actorId: string, action: string, entityType: string, entityId: string, timestamp: number, metadata: Record<string, unknown> = {}) {
  return { text: "INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,occurred_at,metadata_json) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)", params: [crypto.randomUUID(), actorId, action, entityType, entityId, timestamp, json(metadata)] };
}
function event(actorId: string, contractId: string, versionId: string | null, type: string, timestamp: number, metadata: Record<string, unknown> = {}) {
  return { text: "INSERT INTO contract_events(id,contract_id,version_id,actor_user_id,type,occurred_at,metadata_json) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)", params: [crypto.randomUUID(), contractId, versionId, actorId, type, timestamp, json(metadata)] };
}
async function permit(actor: AuthUser, action: ContractAction) { await assertModuleAction(actor, "orders", action); }

const baseSelect = `SELECT c.*,cl.name client_name,cl.phone client_phone,u.display_name responsible_name,o.number order_number,o.source_lead_id,
  rc.name residential_complex,rod.residential_complex_id,rod.residential_complex_address_id,rod.address,rod.apartment_number,rod.area_sqm,cv.version current_version,cv.status current_version_status,
  cv.contract_amount_kopecks,cv.contract_date,p.name project_name
  FROM contracts c JOIN clients cl ON cl.id=c.client_id JOIN users u ON u.id=c.responsible_user_id JOIN orders o ON o.id=c.order_id
  JOIN renovation_order_details rod ON rod.order_id=o.id LEFT JOIN residential_complexes rc ON rc.id=rod.residential_complex_id
  JOIN contract_versions cv ON cv.id=c.current_version_id LEFT JOIN projects p ON p.id=c.project_id`;

type ContractRow = Record<string, unknown> & { id: string; responsible_user_id: string; status: ContractStatus; current_version_id: string; signed_version_id: string | null };
async function visible(actor: AuthUser, contractId: string) {
  await permit(actor, "contracts.view"); const access = await getAccessProfile(actor), scoped = actor.role !== "OWNER" && access.scopes.contracts !== "ALL";
  const row = await first<ContractRow>(`${baseSelect} WHERE c.id=$1${scoped ? " AND c.responsible_user_id=$2" : ""} LIMIT 1`, scoped ? [contractId, actor.id] : [contractId]);
  if (!row) { const exists = await first<{ id: string }>("SELECT id FROM contracts WHERE id=$1", [contractId]); throw new AccessError(exists ? "Нет доступа к этому договору." : "Договор не найден.", exists ? 403 : 404); }
  return row;
}

function summary(row: Record<string, unknown>) {
  return { id: row.id, contractNumber: row.contract_number, clientId: row.client_id, clientName: row.client_name, clientPhone: row.client_phone,
    orderId: row.order_id, orderNumber: row.order_number, projectId: row.project_id, projectName: row.project_name, type: row.type, status: row.status,
    responsibleUserId: row.responsible_user_id, responsibleName: row.responsible_name, currentVersionId: row.current_version_id, currentVersion: Number(row.current_version),
    currentVersionStatus: row.current_version_status, signedVersionId: row.signed_version_id, contractAmountKopecks: Number(row.contract_amount_kopecks), contractDate: row.contract_date,
    residentialComplex: row.residential_complex, residentialComplexId: row.residential_complex_id, residentialComplexAddressId: row.residential_complex_address_id, address: row.address, apartmentNumber: row.apartment_number, areaSqm: row.area_sqm == null ? null : Number(row.area_sqm),
    sourceLeadId: row.source_lead_id, cancellationReason: row.cancellation_reason, createdAt: row.created_at, updatedAt: row.updated_at };
}

export async function listContracts(actor: AuthUser, requestUrl: string) {
  await permit(actor, "contracts.view"); const access = await getAccessProfile(actor), url = new URL(requestUrl), params: unknown[] = [], conditions = ["1=1"];
  const add = (value: unknown) => { params.push(value); return `$${params.length}`; }, search = (url.searchParams.get("search") ?? "").trim().slice(0, 150);
  const status = url.searchParams.get("status") ?? "ALL", responsible = url.searchParams.get("responsibleUserId") ?? "ALL", period = url.searchParams.get("period") ?? "ALL";
  const limit = Math.min(Math.max(Number(url.searchParams.get("limit")) || 30, 1), 100), offset = Math.max(Number(url.searchParams.get("offset")) || 0, 0);
  if (actor.role !== "OWNER" && access.scopes.contracts !== "ALL") conditions.push(`c.responsible_user_id=${add(actor.id)}`);
  if (search) { const like = add(`%${search}%`), digits = add(`%${search.replace(/\D/g, "")}%`); conditions.push(`(c.contract_number ILIKE ${like} OR cl.name ILIKE ${like} OR regexp_replace(cl.phone,'[^0-9]+','','g') LIKE ${digits} OR rc.name ILIKE ${like} OR rod.address ILIKE ${like} OR rod.apartment_number ILIKE ${like} OR o.number ILIKE ${like})`); }
  if (["DRAFT","READY","SENT","SIGNED","CANCELLED","SUPERSEDED"].includes(status)) conditions.push(`c.status=${add(status)}`);
  if (responsible !== "ALL") conditions.push(`c.responsible_user_id=${add(responsible)}`);
  if (period === "30D") conditions.push(`c.created_at>=${add(now()-30*86400)}`); else if (period === "90D") conditions.push(`c.created_at>=${add(now()-90*86400)}`);
  const where = ` WHERE ${conditions.join(" AND ")}`, count = await first<{ count: number | string }>(`SELECT COUNT(*) count FROM contracts c JOIN clients cl ON cl.id=c.client_id JOIN orders o ON o.id=c.order_id JOIN renovation_order_details rod ON rod.order_id=o.id LEFT JOIN residential_complexes rc ON rc.id=rod.residential_complex_id${where}`, params);
  const rows = await query<Record<string, unknown>>(`${baseSelect}${where} ORDER BY c.created_at DESC,c.id DESC LIMIT ${add(limit+1)} OFFSET ${add(offset)}`, params);
  const users = await query<{ id: string; name: string }>("SELECT id,display_name name FROM users WHERE status='ACTIVE' AND role IN ('OWNER','EMPLOYEE') ORDER BY display_name");
  return { items: rows.slice(0,limit).map(summary), total: Number(count?.count ?? 0), hasMore: rows.length>limit, nextOffset: rows.length>limit ? offset+limit : null, users,
    capabilities: { create: actor.role === "OWNER" || access.actions["contracts.create"], companySettings: actor.role === "OWNER" || access.actions["companySettings.view"] } };
}

async function nextNumber() { const row = await first<{ value: number | string }>("SELECT nextval('depa_contract_number_seq') value"); return `ДГ-${String(row?.value ?? 1).padStart(6,"0")}`; }
async function companySnapshot() { return (await first<Record<string, unknown>>("SELECT * FROM company_settings ORDER BY updated_at DESC LIMIT 1")) ?? {}; }
async function activeTemplate() { return first<{ id: string; version: number; body_json: Record<string, unknown> }>("SELECT v.id,v.version,v.body_json FROM contract_template_versions v JOIN contract_templates t ON t.id=v.template_id WHERE t.contract_type='RENOVATION' AND t.status='ACTIVE' AND v.status='ACTIVE' ORDER BY v.published_at DESC NULLS LAST,v.created_at DESC LIMIT 1"); }

export async function createContract(actor: AuthUser, input: ContractInput) {
  await permit(actor, "contracts.create"); const orderId = id(input.orderId); if (!orderId) throw new ContractError("Выберите заказ на ремонт.");
  const access = await getAccessProfile(actor), source = await first<Record<string, unknown>>(`SELECT o.id,o.number,o.client_id,o.responsible_user_id,o.source_lead_id,cl.name client_name,cl.phone,cl.email,
    rod.address,rod.apartment_number,rod.area_sqm,rod.residential_complex_id,rod.residential_complex_address_id,COALESCE(rc.name,rod.residential_complex) residential_complex,rod.approved_estimate_version_id,
    ev.status estimate_status,ev.total_kopecks,ev.estimated_materials_budget_kopecks,ev.planned_duration
    FROM orders o JOIN clients cl ON cl.id=o.client_id JOIN renovation_order_details rod ON rod.order_id=o.id LEFT JOIN residential_complexes rc ON rc.id=rod.residential_complex_id
    LEFT JOIN estimate_versions ev ON ev.id=rod.approved_estimate_version_id WHERE o.id=$1 AND o.type='RENOVATION' LIMIT 1`, [orderId]);
  if (!source) throw new ContractError("Заказ на ремонт не найден.",404); if (source.estimate_status !== "APPROVED") throw new ContractError("Договор создаётся только из согласованной версии сметы.",409);
  if (actor.role !== "OWNER" && access.scopes.contracts !== "ALL" && source.responsible_user_id !== actor.id) throw new AccessError("Нет доступа к этому заказу.",403);
  const existing = await first<{ id: string; contract_number: string }>("SELECT id,contract_number FROM contracts WHERE order_id=$1",[orderId]); if (existing) throw new ContractError("Для этого заказа договор уже создан.",409,{contractId:existing.id,contractNumber:existing.contract_number});
  const contractId=crypto.randomUUID(), versionId=crypto.randomUUID(), timestamp=now(), number=await nextNumber(), company=await companySnapshot(), template=await activeTemplate();
  const client={id:source.client_id,name:source.client_name,phone:source.phone,email:source.email};
  const property={residentialComplexId:source.residential_complex_id,residentialComplexAddressId:source.residential_complex_address_id,residentialComplex:source.residential_complex,address:source.address,apartmentNumber:source.apartment_number,areaSqm:source.area_sqm==null?null:Number(source.area_sqm)};
  const terms={plannedDuration:source.planned_duration,paymentTermsText:clean(input.paymentTermsText,4000),warrantyTerm:clean(input.warrantyTerm,500)};
  await transaction([
    {text:"INSERT INTO contracts(id,contract_number,client_id,order_id,type,status,responsible_user_id,created_by_user_id,created_at,updated_at) VALUES($1,$2,$3,$4,'RENOVATION','DRAFT',$5,$6,$7,$8)",params:[contractId,number,source.client_id,orderId,source.responsible_user_id,actor.id,timestamp,timestamp]},
    {text:`INSERT INTO contract_versions(id,contract_id,version,status,contract_date,estimate_version_id,template_version_id,template_version_number,contract_amount_kopecks,estimated_materials_budget_kopecks,planned_duration,payment_terms_text,warranty_term,client_snapshot_json,company_snapshot_json,property_snapshot_json,terms_snapshot_json,document_snapshot_json,created_by_user_id,created_at,updated_at)
      VALUES($1,$2,1,'DRAFT',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13::jsonb,$14::jsonb,$15::jsonb,$16::jsonb,$17,$18,$19)`,params:[versionId,contractId,integer(input.contractDate),source.approved_estimate_version_id,template?.id??null,template?.version??null,Number(source.total_kopecks),source.estimated_materials_budget_kopecks==null?null:Number(source.estimated_materials_budget_kopecks),source.planned_duration,terms.paymentTermsText,terms.warrantyTerm,json(client),json(company),json(property),json(terms),json({templateReady:Boolean(template),templateBody:template?.body_json??null}),actor.id,timestamp,timestamp]},
    {text:"UPDATE contracts SET current_version_id=$1 WHERE id=$2",params:[versionId,contractId]}, audit(actor.id,"CONTRACT_CREATED","Contract",contractId,timestamp,{orderId,number,estimateVersionId:source.approved_estimate_version_id}), event(actor.id,contractId,versionId,"CONTRACT_CREATED",timestamp,{version:1})]);
  return getContract(actor,contractId);
}

function redactCompany(snapshot: Record<string, unknown>, allowed: boolean) { return allowed ? snapshot : { trade_name: snapshot.trade_name ?? null, detailsRestricted: true }; }
export async function getContract(actor: AuthUser, contractId: string, selectedVersionId?: string | null) {
  const row=await visible(actor,contractId), access=await getAccessProfile(actor), showCompany=actor.role==="OWNER"||access.actions["contracts.viewCompanyDetails"];
  const versions=await query<Record<string,unknown>>(`SELECT v.*,cu.display_name created_by_name,su.display_name sent_by_name,sg.display_name signed_by_name FROM contract_versions v JOIN users cu ON cu.id=v.created_by_user_id LEFT JOIN users su ON su.id=v.sent_by_user_id LEFT JOIN users sg ON sg.id=v.signed_by_user_id WHERE v.contract_id=$1 ORDER BY v.version DESC`,[contractId]);
  const chosen=versions.find(v=>v.id===(selectedVersionId||row.current_version_id))??versions[0]; if(!chosen)throw new ContractError("Версия договора не найдена.",404);
  const files=await query<Record<string,unknown>>("SELECT id,contract_version_id,original_filename,mime_type,size_bytes,category,created_at FROM attachments WHERE contract_version_id=$1 AND upload_status='LINKED' AND deleted_at IS NULL ORDER BY created_at DESC",[chosen.id]);
  const events=await query<Record<string,unknown>>("SELECT e.*,u.display_name actor_name FROM contract_events e JOIN users u ON u.id=e.actor_user_id WHERE e.contract_id=$1 ORDER BY e.occurred_at DESC,e.id DESC",[contractId]);
  const capabilities={edit:actor.role==="OWNER"||access.actions["contracts.edit"],createVersion:actor.role==="OWNER"||access.actions["contracts.createVersion"],markSent:actor.role==="OWNER"||access.actions["contracts.markSent"],markSigned:actor.role==="OWNER"||access.actions["contracts.markSigned"],uploadSigned:actor.role==="OWNER"||access.actions["contracts.uploadSigned"],cancel:actor.role==="OWNER"||access.actions["contracts.cancel"],createProject:actor.role==="OWNER"||access.actions["projects.create"]};
  return {contract:summary(row),version:{...chosen,version:Number(chosen.version),contract_amount_kopecks:Number(chosen.contract_amount_kopecks),estimated_materials_budget_kopecks:chosen.estimated_materials_budget_kopecks==null?null:Number(chosen.estimated_materials_budget_kopecks),company_snapshot_json:redactCompany((chosen.company_snapshot_json??{}) as Record<string,unknown>,showCompany)},versions:versions.map(v=>({...v,company_snapshot_json:redactCompany((v.company_snapshot_json??{}) as Record<string,unknown>,showCompany)})),files,events,capabilities,
    document:{templateReady:Boolean((chosen.document_snapshot_json as Record<string,unknown> | null)?.templateReady),legalReady:Boolean((chosen.document_snapshot_json as Record<string,unknown> | null)?.templateReady)&&Object.keys((chosen.company_snapshot_json??{}) as object).length>0,notice:(chosen.document_snapshot_json as Record<string,unknown> | null)?.templateReady?null:"Шаблон договора не заполнен. Формирование юридического документа недоступно."}};
}

async function currentVersion(actor:AuthUser,contractId:string){const contract=await visible(actor,contractId),version=await first<Record<string,unknown>>("SELECT * FROM contract_versions WHERE id=$1 AND contract_id=$2",[contract.current_version_id,contractId]);if(!version)throw new ContractError("Текущая версия не найдена.",404);return {contract,version};}
export async function saveContractDraft(actor:AuthUser,contractId:string,input:ContractInput){await permit(actor,"contracts.edit");const {version}=await currentVersion(actor,contractId);if(version.status!=="DRAFT")throw new ContractError("Отправленная или подписанная версия неизменяема. Создайте новую версию.",409);const timestamp=now();
  await transaction([{text:"UPDATE contract_versions SET contract_date=$1,planned_start_date=$2,planned_end_date=$3,planned_duration=$4,payment_terms_text=$5,warranty_term=$6,terms_snapshot_json=$7::jsonb,updated_at=$8 WHERE id=$9 AND status='DRAFT'",params:[integer(input.contractDate),integer(input.plannedStartDate),integer(input.plannedEndDate),clean(input.plannedDuration,500),clean(input.paymentTermsText,4000),clean(input.warrantyTerm,500),json({plannedStartDate:integer(input.plannedStartDate),plannedEndDate:integer(input.plannedEndDate),plannedDuration:clean(input.plannedDuration,500),paymentTermsText:clean(input.paymentTermsText,4000),warrantyTerm:clean(input.warrantyTerm,500)}),timestamp,version.id]},{text:"UPDATE contracts SET updated_at=$1 WHERE id=$2",params:[timestamp,contractId]},audit(actor.id,"CONTRACT_DRAFT_UPDATED","ContractVersion",String(version.id),timestamp,{contractId}),event(actor.id,contractId,String(version.id),"CONTRACT_DRAFT_UPDATED",timestamp)]);return getContract(actor,contractId);}

export async function createContractVersion(actor:AuthUser,contractId:string,input:ContractInput){await permit(actor,"contracts.createVersion");const {contract,version}=await currentVersion(actor,contractId);if(contract.status==="CANCELLED")throw new ContractError("Отменённый договор нельзя версионировать.",409);const newId=crypto.randomUUID(),timestamp=now();
  await transaction([{text:"SELECT pg_advisory_xact_lock(hashtext($1))",params:[contractId]},{text:`INSERT INTO contract_versions(id,contract_id,version,status,contract_date,estimate_version_id,template_version_id,template_version_number,contract_amount_kopecks,estimated_materials_budget_kopecks,planned_start_date,planned_end_date,planned_duration,payment_terms_text,warranty_term,client_snapshot_json,company_snapshot_json,property_snapshot_json,terms_snapshot_json,document_snapshot_json,change_reason,created_by_user_id,created_at,updated_at)
    SELECT $1,contract_id,(SELECT COALESCE(MAX(version),0)+1 FROM contract_versions WHERE contract_id=$2),'DRAFT',contract_date,estimate_version_id,template_version_id,template_version_number,contract_amount_kopecks,estimated_materials_budget_kopecks,planned_start_date,planned_end_date,planned_duration,payment_terms_text,warranty_term,client_snapshot_json,company_snapshot_json,property_snapshot_json,terms_snapshot_json,document_snapshot_json,$3,$4,$5,$6 FROM contract_versions WHERE id=$7`,params:[newId,contractId,clean(input.changeReason,2000),actor.id,timestamp,timestamp,version.id]},{text:"UPDATE contract_versions SET status='SUPERSEDED',updated_at=$1 WHERE id=$2 AND status IN ('DRAFT','READY')",params:[timestamp,version.id]},{text:"UPDATE contracts SET current_version_id=$1,status='DRAFT',updated_at=$2 WHERE id=$3",params:[newId,timestamp,contractId]},audit(actor.id,"CONTRACT_VERSION_CREATED","ContractVersion",newId,timestamp,{contractId,sourceVersionId:version.id}),event(actor.id,contractId,newId,"CONTRACT_VERSION_CREATED",timestamp,{sourceVersion:version.version})]);return getContract(actor,contractId);}

async function setStatus(actor:AuthUser,contractId:string,status:"READY"|"SENT"|"SIGNED",input:ContractInput){const permission=status==="SENT"?"contracts.markSent":status==="SIGNED"?"contracts.markSigned":"contracts.edit";await permit(actor,permission);const {contract,version}=await currentVersion(actor,contractId),timestamp=now();if(contract.status==="CANCELLED")throw new ContractError("Договор отменён.",409);
  if(status==="READY"){if(version.status!=="DRAFT")throw new ContractError("К готовности можно перевести только черновик.",409);const doc=(version.document_snapshot_json??{}) as Record<string,unknown>,company=(version.company_snapshot_json??{}) as Record<string,unknown>;if(!doc.templateReady)throw new ContractError("Шаблон договора не заполнен. Юридическая готовность недоступна.",409);if(!company.legal_name||!company.inn||!company.legal_address||!company.director_name)throw new ContractError("Заполните обязательные реквизиты компании.",409);}
  if(status==="SENT"&&!(["READY","SENT"] as unknown[]).includes(version.status))throw new ContractError("Отправить можно только готовую версию.",409);if(status==="SIGNED"&&!(["READY","SENT"] as unknown[]).includes(version.status))throw new ContractError("Подписать можно только готовую или отправленную версию.",409);if(status==="SIGNED"&&actor.role!=="OWNER"&&!id(input.attachmentId))throw new ContractError("Без подписанного файла отметить договор может только Owner.",403);
  if(status==="SIGNED"&&id(input.attachmentId))await linkSignedAttachment(actor,contractId,{...input,versionId:version.id});
  const versionStatement=status==="SENT"?{text:"UPDATE contract_versions SET status='SENT',sent_at=$1,sent_by_user_id=$2,updated_at=$3 WHERE id=$4",params:[timestamp,actor.id,timestamp,version.id]}:status==="SIGNED"?{text:"UPDATE contract_versions SET status='SIGNED',signed_at=$1,signed_by_user_id=$2,signature_note=$3,updated_at=$4 WHERE id=$5",params:[timestamp,actor.id,clean(input.signatureNote,2000),timestamp,version.id]}:{text:"UPDATE contract_versions SET status='READY',updated_at=$1 WHERE id=$2",params:[timestamp,version.id]};
  await transaction([versionStatement,{text:"UPDATE contracts SET status=$1,signed_version_id=CASE WHEN $1='SIGNED' THEN $2 ELSE signed_version_id END,updated_at=$3 WHERE id=$4",params:[status,version.id,timestamp,contractId]},audit(actor.id,`CONTRACT_${status}`,"Contract",contractId,timestamp,{versionId:version.id,withoutFile:status==="SIGNED"&&!id(input.attachmentId)}),event(actor.id,contractId,String(version.id),`CONTRACT_${status}`,timestamp)]);return getContract(actor,contractId);}
export const markContractReady=(actor:AuthUser,id:string,input:ContractInput)=>setStatus(actor,id,"READY",input);export const markContractSent=(actor:AuthUser,id:string,input:ContractInput)=>setStatus(actor,id,"SENT",input);export const markContractSigned=(actor:AuthUser,id:string,input:ContractInput)=>setStatus(actor,id,"SIGNED",input);

export async function linkSignedAttachment(actor:AuthUser,contractId:string,input:ContractInput){await permit(actor,"contracts.uploadSigned");await visible(actor,contractId);const attachmentId=id(input.attachmentId),versionId=id(input.versionId);if(!attachmentId||!versionId)throw new ContractError("Не указан файл или версия.");const attachment=await confirmAttachmentUpload(actor,attachmentId);if(!["SIGNED_CONTRACT","CONTRACT_PDF","CONTRACT_OTHER"].includes(attachment.category))throw new ContractError("Некорректная категория файла.");const version=await first<{id:string}>("SELECT id FROM contract_versions WHERE id=$1 AND contract_id=$2",[versionId,contractId]);if(!version)throw new ContractError("Версия договора не найдена.",404);const timestamp=now();await transaction([{text:"UPDATE attachments SET contract_version_id=$1,entity_type='ContractVersion',entity_id=$1,upload_status='LINKED',linked_at=$2,updated_at=$3 WHERE id=$4 AND uploaded_by_user_id=$5 AND upload_status='UPLOADED'",params:[versionId,timestamp,timestamp,attachmentId,actor.id]},audit(actor.id,"CONTRACT_FILE_LINKED","Attachment",attachmentId,timestamp,{contractId,versionId}),event(actor.id,contractId,versionId,"CONTRACT_FILE_LINKED",timestamp,{attachmentId,category:attachment.category})]);return {ok:true,attachmentId};}

export async function cancelContract(actor:AuthUser,contractId:string,input:ContractInput){await permit(actor,"contracts.cancel");const contract=await visible(actor,contractId),reason=clean(input.reason,2000);if(!reason)throw new ContractError("Укажите причину отмены.");if(contract.status==="CANCELLED")return getContract(actor,contractId);const timestamp=now();await transaction([{text:"UPDATE contracts SET status='CANCELLED',cancelled_at=$1,cancelled_by_user_id=$2,cancellation_reason=$3,updated_at=$4 WHERE id=$5",params:[timestamp,actor.id,reason,timestamp,contractId]},audit(actor.id,"CONTRACT_CANCELLED","Contract",contractId,timestamp,{reason}),event(actor.id,contractId,null,"CONTRACT_CANCELLED",timestamp,{reason})]);return getContract(actor,contractId);}

export async function createContractFollowUp(actor:AuthUser,contractId:string,input:ContractInput){await assertModuleAction(actor,"crm","crm.edit");const contract=await visible(actor,contractId),leadId=contract.source_lead_id as string|null;if(!leadId)throw new ContractError("У договора нет связанной CRM-заявки.",409);const scheduledAt=Number(input.scheduledAt);if(!Number.isInteger(scheduledAt)||scheduledAt<=now())throw new ContractError("Укажите будущую дату следующего действия.");const timestamp=now(),activityId=crypto.randomUUID(),comment=clean(input.comment,1000);await transaction([{text:"UPDATE lead_activities SET status='CANCELLED',updated_at=$1 WHERE lead_id=$2 AND status='SCHEDULED'",params:[timestamp,leadId]},{text:"INSERT INTO lead_activities(id,lead_id,type,status,scheduled_at,comment,created_by_user_id,created_at,updated_at) VALUES($1,$2,'FOLLOW_UP_CONTRACT','SCHEDULED',$3,$4,$5,$6,$7)",params:[activityId,leadId,scheduledAt,comment,actor.id,timestamp,timestamp]},{text:"UPDATE leads SET next_action_type='FOLLOW_UP_CONTRACT',next_action_at=$1,next_action_comment=$2,updated_at=$3 WHERE id=$4",params:[scheduledAt,comment,timestamp,leadId]},audit(actor.id,"LEAD_ACTIVITY_CREATED","LeadActivity",activityId,timestamp,{leadId,type:"FOLLOW_UP_CONTRACT",contractId}),event(actor.id,contractId,contract.current_version_id,"CONTRACT_FOLLOW_UP_CREATED",timestamp,{leadId,scheduledAt})]);return {ok:true,activityId};}

const companyFields=["legalName","tradeName","inn","kpp","ogrn","legalAddress","postalAddress","bankName","bankAccount","correspondentAccount","bik","directorName","directorTitle","actingBasis","phone","email"] as const;
const companyColumns:{[K in typeof companyFields[number]]:string}={legalName:"legal_name",tradeName:"trade_name",inn:"inn",kpp:"kpp",ogrn:"ogrn",legalAddress:"legal_address",postalAddress:"postal_address",bankName:"bank_name",bankAccount:"bank_account",correspondentAccount:"correspondent_account",bik:"bik",directorName:"director_name",directorTitle:"director_title",actingBasis:"acting_basis",phone:"phone",email:"email"};
export async function getCompanySettings(actor:AuthUser){await permit(actor,"companySettings.view");return {settings:await first<Record<string,unknown>>("SELECT * FROM company_settings ORDER BY updated_at DESC LIMIT 1"),canEdit:actor.role==="OWNER"};}
export async function saveCompanySettings(actor:AuthUser,input:ContractInput){if(actor.role!=="OWNER")throw new AccessError("Редактировать реквизиты компании может только Owner.",403);await permit(actor,"companySettings.edit");const values=companyFields.map(field=>clean(input[field],field.includes("Address")?1000:300)),timestamp=now(),existing=await first<{id:string}>("SELECT id FROM company_settings ORDER BY updated_at DESC LIMIT 1"),settingsId=existing?.id??crypto.randomUUID();const columns=companyFields.map(field=>companyColumns[field]);
  if(existing)await query(`UPDATE company_settings SET ${columns.map((column,index)=>`${column}=$${index+1}`).join(",")},updated_by_user_id=$17,updated_at=$18 WHERE id=$19`,[...values,actor.id,timestamp,settingsId]);else await query(`INSERT INTO company_settings(id,${columns.join(",")},updated_by_user_id,created_at,updated_at) VALUES($1,${columns.map((_,index)=>`$${index+2}`).join(",")},$18,$19,$20)`,[settingsId,...values,actor.id,timestamp,timestamp]);await query("INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,occurred_at,metadata_json) VALUES($1,$2,'COMPANY_SETTINGS_UPDATED','CompanySettings',$3,$4,'{}')",[crypto.randomUUID(),actor.id,settingsId,timestamp]);return getCompanySettings(actor);}
