import type { AuthUser } from "./auth";
import { normalizePhone } from "./client-config";
import { LEAD_ACTIONS, LEAD_SOURCES, LEAD_STAGES, LOST_REASONS, type LeadActionType, type LeadStage } from "./crm-config";
import { first, query, transaction } from "./postgres";
import { AccessError, assertModuleAction, getAccessProfile } from "./permissions";

type LeadRow = { id:string;name:string;phone:string;normalized_phone:string;secondary_phone:string|null;email:string|null;preferred_contact:string|null;source:string;stage:LeadStage;responsible_user_id:string;responsible_name:string;linked_client_id:string|null;linked_client_name:string|null;comment:string|null;next_action_type:LeadActionType|null;next_action_at:number|null;next_action_comment:string|null;lost_reason:string|null;lost_comment:string|null;created_by_user_id:string;created_at:number;updated_at:number;closed_at:number|null };
type ActivityRow = { id:string;type:string;status:string;scheduled_at:number|null;completed_at:number|null;comment:string|null;created_at:number;created_by_name:string;completed_by_name:string|null };
export type LeadInput = Record<string, unknown>;

export class CrmError extends Error {
  constructor(message:string,public status=400,public details?:Record<string,unknown>){super(message);}
}
function clean(value:unknown,max:number){if(typeof value!=="string")return null;const text=value.trim();return text?text.slice(0,max):null;}
function seconds(value:unknown){if(value==null||value==="")return null;if(typeof value==="number")return Number.isFinite(value)?Math.floor(value):null;const date=new Date(String(value));return Number.isNaN(date.getTime())?null:Math.floor(date.getTime()/1000);}
function leadSelect(){return `SELECT l.id,l.name,l.phone,l.normalized_phone,l.secondary_phone,l.email,l.preferred_contact,l.source,l.stage,l.responsible_user_id,ru.display_name AS responsible_name,l.linked_client_id,c.name AS linked_client_name,l.comment,l.next_action_type,l.next_action_at,l.next_action_comment,l.lost_reason,l.lost_comment,l.created_by_user_id,l.created_at,l.updated_at,l.closed_at FROM leads l JOIN users ru ON ru.id=l.responsible_user_id LEFT JOIN clients c ON c.id=l.linked_client_id`;}
function serialize(row:LeadRow){return {id:row.id,name:row.name,phone:row.phone,normalizedPhone:row.normalized_phone,secondaryPhone:row.secondary_phone,email:row.email,preferredContact:row.preferred_contact,source:row.source,stage:row.stage,responsibleUserId:row.responsible_user_id,responsibleName:row.responsible_name,linkedClientId:row.linked_client_id,linkedClientName:row.linked_client_name,comment:row.comment,nextActionType:row.next_action_type,nextActionAt:row.next_action_at,nextActionComment:row.next_action_comment,lostReason:row.lost_reason,lostComment:row.lost_comment,createdByUserId:row.created_by_user_id,createdAt:row.created_at,updatedAt:row.updated_at,closedAt:row.closed_at};}
function serializeActivity(row:ActivityRow){return {id:row.id,type:row.type,status:row.status,scheduledAt:row.scheduled_at,completedAt:row.completed_at,comment:row.comment,createdAt:row.created_at,createdByName:row.created_by_name,completedByName:row.completed_by_name};}
async function assertResponsible(userId:string){const row=await first<{id:string}>(`SELECT u.id FROM users u WHERE u.id=$1 AND u.status='ACTIVE' AND (u.role='OWNER' OR EXISTS(SELECT 1 FROM user_permissions p WHERE p.user_id=u.id AND p.permission='modules.crm.view' AND p.scope='COMPANY' AND p.allowed=1)) LIMIT 1`,[userId]);if(!row)throw new CrmError("Выбранный пользователь не может работать с CRM.");}
export async function listCrmUsers(){return query<{id:string;name:string}>(`SELECT u.id,u.display_name AS name FROM users u WHERE u.status='ACTIVE' AND (u.role='OWNER' OR EXISTS(SELECT 1 FROM user_permissions p WHERE p.user_id=u.id AND p.permission='modules.crm.view' AND p.scope='COMPANY' AND p.allowed=1)) ORDER BY CASE WHEN u.role='OWNER' THEN 0 ELSE 1 END,u.display_name`);}
function scopeSql(actor:AuthUser,all:boolean,param:number){return actor.role==="OWNER"||all?{sql:"",params:[] as unknown[]}:{sql:` AND l.responsible_user_id=$${param}`,params:[actor.id] as unknown[]};}

export async function listLeads(actor:AuthUser,requestUrl:string){
  await assertModuleAction(actor,"crm","crm.view");const access=await getAccessProfile(actor);const url=new URL(requestUrl);const attention=url.searchParams.get("attention")==="1";const view=url.searchParams.get("view")||"list";const search=(url.searchParams.get("search")||"").trim().slice(0,120);const source=url.searchParams.get("source")||"ALL";const stage=url.searchParams.get("stage")||"ALL";const responsible=url.searchParams.get("responsibleUserId")||"ALL";const status=url.searchParams.get("status")||"ACTIVE";const actionFilter=url.searchParams.get("action")||"ALL";const limit=Math.min(Math.max(Number(url.searchParams.get("limit"))||30,1),100);const offset=Math.max(Number(url.searchParams.get("offset"))||0,0);const params:unknown[]=[];const conditions:string[]=[];const add=(v:unknown)=>{params.push(v);return `$${params.length}`;};
  if(actor.role!=="OWNER"&&access.scopes.crm!=="ALL")conditions.push(`l.responsible_user_id=${add(actor.id)}`);
  if(search){const term=`%${search}%`,digits=normalizePhone(search);conditions.push(`(l.name ILIKE ${add(term)} OR l.normalized_phone LIKE ${add(digits?`%${digits}%`:"__NO_PHONE__")} OR l.email ILIKE ${add(term)} OR c.name ILIKE ${add(term)})`);}
  if(LEAD_SOURCES.some(x=>x.value===source))conditions.push(`l.source=${add(source)}`);if(LEAD_STAGES.some(x=>x.value===stage))conditions.push(`l.stage=${add(stage)}`);if(responsible!=="ALL")conditions.push(`l.responsible_user_id=${add(responsible)}`);
  if(status==="ACTIVE")conditions.push(`l.stage NOT IN ('WON','LOST')`);else if(status==="WON")conditions.push(`l.stage='WON'`);else if(status==="LOST")conditions.push(`l.stage='LOST'`);
  const now=Math.floor(Date.now()/1000),vladivostokOffset=10*3600,dayStart=Math.floor((now+vladivostokOffset)/86400)*86400-vladivostokOffset;
  if(attention){conditions.push(`l.stage NOT IN ('WON','LOST') AND l.next_action_at IS NOT NULL AND l.next_action_at<=${add(now+7*86400)}`);}else if(actionFilter==="TODAY")conditions.push(`l.next_action_at BETWEEN ${add(dayStart)} AND ${add(dayStart+86400-1)}`);else if(actionFilter==="OVERDUE")conditions.push(`l.next_action_at<${add(now)}`);else if(actionFilter==="NONE")conditions.push(`l.next_action_at IS NULL`);
  const where=conditions.length?` WHERE ${conditions.join(" AND ")}`:"";const count=await first<{count:number|string}>(`SELECT COUNT(*) count FROM leads l LEFT JOIN clients c ON c.id=l.linked_client_id${where}`,params);
  let rows:LeadRow[];if(view==="kanban"&&!attention){rows=await query<LeadRow>(`WITH ranked AS (SELECT l.*,ROW_NUMBER() OVER(PARTITION BY l.stage ORDER BY l.created_at DESC,l.id DESC) rn FROM leads l LEFT JOIN clients c ON c.id=l.linked_client_id${where}) SELECT r.id,r.name,r.phone,r.normalized_phone,r.secondary_phone,r.email,r.preferred_contact,r.source,r.stage,r.responsible_user_id,u.display_name responsible_name,r.linked_client_id,c.name linked_client_name,r.comment,r.next_action_type,r.next_action_at,r.next_action_comment,r.lost_reason,r.lost_comment,r.created_by_user_id,r.created_at,r.updated_at,r.closed_at FROM ranked r JOIN users u ON u.id=r.responsible_user_id LEFT JOIN clients c ON c.id=r.linked_client_id WHERE r.rn<=30 ORDER BY r.stage,r.created_at DESC`,params);}else{rows=await query<LeadRow>(`${leadSelect()}${where} ORDER BY ${attention?"l.next_action_at ASC":"l.created_at DESC,l.id DESC"} LIMIT ${add(attention?7:limit+1)}${attention?"":` OFFSET ${add(offset)}`}`,params);}
  const stageRows=await query<{stage:string;count:number|string}>(`SELECT l.stage,COUNT(*) count FROM leads l LEFT JOIN clients c ON c.id=l.linked_client_id${where} GROUP BY l.stage`,params);const stageCounts=Object.fromEntries(stageRows.map(row=>[row.stage,Number(row.count)]));
  const hasMore=!attention&&view!=="kanban"&&rows.length>limit;return {items:rows.slice(0,attention?7:view==="kanban"?rows.length:limit).map(serialize),total:Number(count?.count||0),stageCounts,hasMore,nextOffset:hasMore?offset+limit:null,responsibleUsers:await listCrmUsers(),sources:LEAD_SOURCES,stages:LEAD_STAGES,actions:LEAD_ACTIONS,lostReasons:LOST_REASONS};
}

async function visibleLead(actor:AuthUser,id:string){await assertModuleAction(actor,"crm","crm.view");const access=await getAccessProfile(actor);const scope=scopeSql(actor,access.scopes.crm==="ALL",2);const row=await first<LeadRow>(`${leadSelect()} WHERE l.id=$1${scope.sql} LIMIT 1`,[id,...scope.params]);if(!row){const exists=await first<{id:string}>("SELECT id FROM leads WHERE id=$1",[id]);throw new AccessError(exists?"Нет доступа к этой заявке.":"Заявка не найдена.",exists?403:404);}return row;}
export async function getLead(actor:AuthUser,id:string){const row=await visibleLead(actor,id);const access=await getAccessProfile(actor);const activities=await query<ActivityRow>(`SELECT a.id,a.type,a.status,a.scheduled_at,a.completed_at,a.comment,a.created_at,cu.display_name created_by_name,du.display_name completed_by_name FROM lead_activities a JOIN users cu ON cu.id=a.created_by_user_id LEFT JOIN users du ON du.id=a.completed_by_user_id WHERE a.lead_id=$1 ORDER BY COALESCE(a.scheduled_at,a.created_at) DESC,a.created_at DESC`,[id]);return {lead:serialize(row),activities:activities.map(serializeActivity),capabilities:{edit:actor.role==="OWNER"||access.actions["crm.edit"],changeStatus:actor.role==="OWNER"||access.actions["crm.changeStatus"],assign:actor.role==="OWNER"||access.actions["crm.assign"],close:actor.role==="OWNER"||access.actions["crm.close"],createClient:actor.role==="OWNER"||(access.modules.clients&&access.actions["clients.create"]),viewClient:actor.role==="OWNER"||(access.modules.clients&&access.actions["clients.view"]),createOrder:false}};}

function validated(input:LeadInput,actor:AuthUser,before?:LeadRow){const name=clean(input.name,180)??before?.name;const phone=clean(input.phone,80)??before?.phone;const source=clean(input.source,30)??before?.source;const stage=(clean(input.stage,30)??before?.stage??"NEW") as LeadStage;const responsibleUserId=clean(input.responsibleUserId,100)??before?.responsible_user_id??actor.id;if(!name)throw new CrmError("Укажите имя или ФИО.");if(!phone||normalizePhone(phone).length<5)throw new CrmError("Укажите корректный телефон.");if(!LEAD_SOURCES.some(x=>x.value===source))throw new CrmError("Выберите источник.");if(!LEAD_STAGES.some(x=>x.value===stage))throw new CrmError("Некорректный этап.");const email=input.email===undefined?before?.email??null:clean(input.email,180);if(email&&!/^\S+@\S+\.\S+$/.test(email))throw new CrmError("Проверьте email.");return {name,phone,normalizedPhone:normalizePhone(phone),secondaryPhone:input.secondaryPhone===undefined?before?.secondary_phone??null:clean(input.secondaryPhone,80),email,preferredContact:input.preferredContact===undefined?before?.preferred_contact??null:clean(input.preferredContact,30),source,stage,responsibleUserId,linkedClientId:input.linkedClientId===undefined?before?.linked_client_id??null:clean(input.linkedClientId,100),comment:input.comment===undefined?before?.comment??null:clean(input.comment,4000)};}
export async function duplicateCheck(actor:AuthUser,phone:string,excludeId?:string){await assertModuleAction(actor,"crm","crm.view");const normalized=normalizePhone(phone);if(normalized.length<5)return {lead:null,client:null};const access=await getAccessProfile(actor);const params:unknown[]=[normalized];let extra="";if(excludeId){params.push(excludeId);extra=` AND l.id<>$${params.length}`;}if(actor.role!=="OWNER"&&access.scopes.crm!=="ALL"){params.push(actor.id);extra+=` AND l.responsible_user_id=$${params.length}`;}const lead=await first<LeadRow>(`${leadSelect()} WHERE l.normalized_phone=$1 AND l.stage NOT IN ('WON','LOST')${extra} ORDER BY l.created_at DESC LIMIT 1`,params);const client=actor.role==="OWNER"||(access.modules.clients&&access.actions["clients.view"])?await first<{id:string;name:string;phone:string}>("SELECT id,name,phone FROM clients WHERE phone_normalized=$1 AND status='ACTIVE' ORDER BY created_at DESC LIMIT 1",[normalized]):null;return {lead:lead?serialize(lead):null,client};}
export async function createLead(actor:AuthUser,input:LeadInput,force=false){await assertModuleAction(actor,"crm","crm.create");const data=validated(input,actor);await assertResponsible(data.responsibleUserId);const duplicate=await duplicateCheck(actor,data.phone);if((duplicate.lead||duplicate.client)&&!force)throw new CrmError("Возможный дубль заявки.",409,duplicate);const id=crypto.randomUUID(),now=Math.floor(Date.now()/1000);await transaction([{text:`INSERT INTO leads(id,name,phone,normalized_phone,secondary_phone,email,preferred_contact,source,stage,responsible_user_id,linked_client_id,comment,created_by_user_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`,params:[id,data.name,data.phone,data.normalizedPhone,data.secondaryPhone,data.email,data.preferredContact,data.source,data.stage,data.responsibleUserId,data.linkedClientId,data.comment,actor.id,now,now]},{text:"INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,occurred_at,metadata_json) VALUES($1,$2,'LEAD_CREATED','Lead',$3,$4,$5)",params:[crypto.randomUUID(),actor.id,id,now,JSON.stringify({source:data.source,stage:data.stage,responsibleUserId:data.responsibleUserId})]}]);if(input.nextActionType)await createActivity(actor,id,input);return getLead(actor,id);}

export async function updateLead(actor:AuthUser,id:string,input:LeadInput){await assertModuleAction(actor,"crm","crm.edit");const before=await visibleLead(actor,id);const access=await getAccessProfile(actor);const data=validated(input,actor,before);if(before.responsible_user_id!==data.responsibleUserId&&actor.role!=="OWNER"&&!access.actions["crm.assign"])throw new AccessError("Нет права менять ответственного.");if(before.stage!==data.stage){if(["WON","LOST"].includes(data.stage)&&actor.role!=="OWNER"&&!access.actions["crm.close"])throw new AccessError("Нет права закрывать заявки.");if(!["WON","LOST"].includes(data.stage)&&actor.role!=="OWNER"&&!access.actions["crm.changeStatus"])throw new AccessError("Нет права менять этап.");if(data.stage==="WON"&&!data.linkedClientId)throw new CrmError("Перед успешным закрытием создайте или свяжите клиента.",409,{requiresClient:true});if(data.stage==="LOST"&&!clean(input.lostReason,40))throw new CrmError("Укажите причину отказа.");}
  const now=Math.floor(Date.now()/1000),lostReason=data.stage==="LOST"?clean(input.lostReason,40):before.lost_reason,lostComment=data.stage==="LOST"?clean(input.lostComment,1000):before.lost_comment,closedAt=["WON","LOST"].includes(data.stage)?(["WON","LOST"].includes(before.stage)?before.closed_at??now:now):null;const statements=[{text:`UPDATE leads SET name=$1,phone=$2,normalized_phone=$3,secondary_phone=$4,email=$5,preferred_contact=$6,source=$7,stage=$8,responsible_user_id=$9,linked_client_id=$10,comment=$11,lost_reason=$12,lost_comment=$13,closed_at=$14,updated_at=$15 WHERE id=$16`,params:[data.name,data.phone,data.normalizedPhone,data.secondaryPhone,data.email,data.preferredContact,data.source,data.stage,data.responsibleUserId,data.linkedClientId,data.comment,lostReason,lostComment,closedAt,now,id]},{text:"INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,occurred_at,metadata_json) VALUES($1,$2,'LEAD_UPDATED','Lead',$3,$4,$5)",params:[crypto.randomUUID(),actor.id,id,now,JSON.stringify({stage:data.stage})]}];
  if(before.stage!==data.stage){const metadata=JSON.stringify({from:before.stage,to:data.stage,lostReason});statements.push({text:"INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,occurred_at,metadata_json) VALUES($1,$2,'LEAD_STAGE_CHANGED','Lead',$3,$4,$5)",params:[crypto.randomUUID(),actor.id,id,now,metadata]});const special=data.stage==="WON"?"LEAD_WON":data.stage==="LOST"?"LEAD_LOST":before.stage==="LOST"?"LEAD_REOPENED":null;if(special)statements.push({text:"INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,occurred_at,metadata_json) VALUES($1,$2,$3,'Lead',$4,$5,$6)",params:[crypto.randomUUID(),actor.id,special,id,now,metadata]});}
  if(before.responsible_user_id!==data.responsibleUserId)statements.push({text:"INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,occurred_at,metadata_json) VALUES($1,$2,'LEAD_RESPONSIBLE_CHANGED','Lead',$3,$4,$5)",params:[crypto.randomUUID(),actor.id,id,now,JSON.stringify({from:before.responsible_user_id,to:data.responsibleUserId})]});
  if(before.linked_client_id!==data.linkedClientId)statements.push({text:"INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,occurred_at,metadata_json) VALUES($1,$2,$3,'Lead',$4,$5,$6)",params:[crypto.randomUUID(),actor.id,data.linkedClientId?"LEAD_CLIENT_LINKED":"LEAD_CLIENT_UNLINKED",id,now,JSON.stringify({from:before.linked_client_id,to:data.linkedClientId})]});await transaction(statements);return getLead(actor,id);}

export async function createActivity(actor:AuthUser,leadId:string,input:LeadInput){await assertModuleAction(actor,"crm","crm.edit");await visibleLead(actor,leadId);const type=clean(input.nextActionType??input.type,40) as LeadActionType|null;if(!type||!LEAD_ACTIONS.some(x=>x[0]===type))throw new CrmError("Выберите следующее действие.");const scheduledAt=seconds(input.nextActionAt??input.scheduledAt);if(!scheduledAt)throw new CrmError("Укажите дату и время действия.");const comment=clean(input.nextActionComment??input.comment,1000),id=crypto.randomUUID(),now=Math.floor(Date.now()/1000);await transaction([{text:"UPDATE lead_activities SET status='CANCELLED',updated_at=$1 WHERE lead_id=$2 AND status='SCHEDULED'",params:[now,leadId]},{text:"INSERT INTO lead_activities(id,lead_id,type,status,scheduled_at,comment,created_by_user_id,created_at,updated_at) VALUES($1,$2,$3,'SCHEDULED',$4,$5,$6,$7,$8)",params:[id,leadId,type,scheduledAt,comment,actor.id,now,now]},{text:"UPDATE leads SET next_action_type=$1,next_action_at=$2,next_action_comment=$3,updated_at=$4 WHERE id=$5",params:[type,scheduledAt,comment,now,leadId]},{text:"INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,occurred_at,metadata_json) VALUES($1,$2,'LEAD_ACTIVITY_CREATED','LeadActivity',$3,$4,$5)",params:[crypto.randomUUID(),actor.id,id,now,JSON.stringify({leadId,type,scheduledAt})]},{text:"INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,occurred_at,metadata_json) VALUES($1,$2,'LEAD_NEXT_ACTION_CHANGED','Lead',$3,$4,$5)",params:[crypto.randomUUID(),actor.id,leadId,now,JSON.stringify({type,scheduledAt})]}]);return getLead(actor,leadId);}
export async function completeActivity(actor:AuthUser,leadId:string,activityId:string,cancel=false){await assertModuleAction(actor,"crm","crm.edit");await visibleLead(actor,leadId);const activity=await first<{id:string;status:string}>("SELECT id,status FROM lead_activities WHERE id=$1 AND lead_id=$2",[activityId,leadId]);if(!activity)throw new CrmError("Действие не найдено.",404);if(activity.status!=="SCHEDULED")throw new CrmError("Это действие уже завершено или отменено.",409);const now=Math.floor(Date.now()/1000),status=cancel?"CANCELLED":"COMPLETED";await transaction([{text:"UPDATE lead_activities SET status=$1,completed_at=$2,completed_by_user_id=$3,updated_at=$4 WHERE id=$5 AND status='SCHEDULED'",params:[status,cancel?null:now,cancel?null:actor.id,now,activityId]},{text:"UPDATE leads SET next_action_type=NULL,next_action_at=NULL,next_action_comment=NULL,updated_at=$1 WHERE id=$2",params:[now,leadId]},{text:"INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,occurred_at,metadata_json) VALUES($1,$2,$3,'LeadActivity',$4,$5,$6)",params:[crypto.randomUUID(),actor.id,cancel?"LEAD_ACTIVITY_CANCELLED":"LEAD_ACTIVITY_COMPLETED",activityId,now,JSON.stringify({leadId})]}]);return getLead(actor,leadId);}
