import type { AuthUser } from "./auth";
import type { ClientPortalUser } from "./client-portal";
import { first, query, transaction } from "./postgres";
import { AccessError, assertModuleAction, canViewProject, getAccessProfile } from "./permissions";

const now = () => Math.floor(Date.now() / 1000);
const id = () => crypto.randomUUID();
const clean = (value: unknown, max = 2_000) => typeof value === "string" ? value.trim().replace(/[\u0000-\u001f\u007f]/g, "").slice(0, max) : "";
const OPEN_DEFECTS = "('OPEN','IN_PROGRESS','RESOLVED','DISPUTED')";

export class HandoverError extends Error { constructor(message: string, public status = 400, public details: Record<string, unknown> = {}) { super(message); } }

type HandoverRow = { id: string; project_id: string; client_id: string; status: string; current_round_id: string | null; accepted_at: number | null; project_name: string; address: string; apartment: string };

function employeeAudit(actor: AuthUser, action: string, entityId: string, metadata: Record<string, unknown>, at: number) { return { text: "INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,occurred_at,metadata_json) VALUES($1,$2,$3,'ProjectHandover',$4,$5,$6::jsonb)", params: [id(), actor.id, action, entityId, at, JSON.stringify(metadata)] }; }
function employeeEvent(handover: HandoverRow, actor: AuthUser, type: string, timestamp: number, roundId: string | null = null, comment: string | null = null, metadata: Record<string, unknown> = {}) { return { text: "INSERT INTO project_handover_events(id,handover_id,project_id,round_id,type,employee_user_id,comment,metadata_json,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9)", params: [id(), handover.id, handover.project_id, roundId, type, actor.id, comment, JSON.stringify(metadata), timestamp] }; }
function clientEvent(handover: HandoverRow, user: ClientPortalUser, type: string, timestamp: number, roundId: string | null = null, comment: string | null = null) { return { text: "INSERT INTO project_handover_events(id,handover_id,project_id,round_id,type,client_portal_user_id,comment,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)", params: [id(), handover.id, handover.project_id, roundId, type, user.id, comment, timestamp] }; }
function defectEvent(defect: { id: string; handover_id: string; project_id: string }, type: string, timestamp: number, actor: { employee?: string; client?: string }, comment: string | null = null) { return { text: "INSERT INTO project_handover_defect_events(id,defect_id,handover_id,project_id,type,employee_user_id,client_portal_user_id,comment,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)", params: [id(), defect.id, defect.handover_id, defect.project_id, type, actor.employee ?? null, actor.client ?? null, comment, timestamp] }; }

async function permit(actor: AuthUser, permission: Parameters<typeof assertModuleAction>[2], projectId: string) {
  await assertModuleAction(actor, "projects", permission);
  if (!(await canViewProject(actor, projectId))) throw new AccessError("Финальная сдача этого объекта недоступна.", 403);
  if (actor.role !== "OWNER" && (await getAccessProfile(actor)).scopes.handover !== "ALL" && !(await canViewProject(actor, projectId))) throw new AccessError();
}
async function handoverRow(projectId: string) { return first<HandoverRow>(`SELECT h.*,p.client_id,p.name project_name,p.address,p.apartment FROM project_handovers h JOIN projects p ON p.id=h.project_id WHERE h.project_id=$1`, [projectId]); }
async function requireHandover(projectId: string) { const row = await handoverRow(projectId); if (!row) throw new HandoverError("Финальная сдача ещё не подготовлена.", 404); return row; }
async function clientHandover(user: ClientPortalUser, projectId: string) { const row = await first<HandoverRow>(`SELECT h.*,p.client_id,p.name project_name,p.address,p.apartment FROM project_handovers h JOIN projects p ON p.id=h.project_id WHERE h.project_id=$1 AND p.client_id=$2`, [projectId, user.clientId]); if (!row) throw new HandoverError("Финальная сдача недоступна.", 404); return row; }

export async function getHandoverReadiness(actor: AuthUser, projectId: string) {
  await permit(actor, "handover.view", projectId);
  const project = await first<{ id: string; published_forecast_end_date: number | null }>("SELECT id,published_forecast_end_date FROM projects WHERE id=$1 AND archived_at IS NULL", [projectId]);
  if (!project) throw new HandoverError("Объект не найден.", 404);
  const [plan, stages, tasks, hidden, additional, obligations, claims] = await Promise.all([
    first<{ id: string }>("SELECT id FROM production_plans WHERE project_id=$1 AND status='ACTIVE'", [projectId]),
    first<{ total: number; incomplete: number }>("SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status<>'COMPLETED')::int incomplete FROM project_stages WHERE project_id=$1 AND archived_at IS NULL", [projectId]),
    first<{ active: number }>("SELECT COUNT(*) FILTER(WHERE status NOT IN('COMPLETED','CANCELLED'))::int active FROM tasks WHERE project_id=$1 AND production_plan_id IS NOT NULL AND archived_at IS NULL", [projectId]),
    first<{ missing: number }>(`SELECT COUNT(*)::int missing FROM task_photo_requirements r JOIN tasks t ON t.id=r.task_id WHERE t.project_id=$1 AND r.required_before_completion=1 AND NOT EXISTS(SELECT 1 FROM attachments a WHERE a.photo_requirement_id=r.id AND a.upload_status='LINKED' AND a.deleted_at IS NULL)`, [projectId]),
    first<{ active: number; approved_without_tasks: number }>(`SELECT COUNT(*) FILTER(WHERE aw.status NOT IN('APPROVED','REJECTED','CANCELLED','SUPERSEDED'))::int active,COUNT(*) FILTER(WHERE aw.status='APPROVED' AND NOT EXISTS(SELECT 1 FROM additional_work_task_links l WHERE l.additional_work_id=aw.id))::int approved_without_tasks FROM additional_works aw WHERE aw.project_id=$1`, [projectId]),
    first<{ open: number }>("SELECT COUNT(*) FILTER(WHERE status IN('OPEN','PARTIALLY_PAID'))::int open FROM obligations WHERE project_id=$1", [projectId]),
    first<{ pending: number }>("SELECT COUNT(*) FILTER(WHERE status='PENDING')::int pending FROM client_payment_claims WHERE project_id=$1", [projectId]),
  ]);
  const blockers: { code: string; message: string }[] = [], warnings: { code: string; message: string }[] = [];
  if (!plan) blockers.push({ code: "NO_PRODUCTION_PLAN", message: "Производственный план не создан." });
  if (!Number(stages?.total ?? 0)) blockers.push({ code: "NO_STAGES", message: "В производственном плане нет этапов." });
  if (Number(stages?.incomplete ?? 0)) blockers.push({ code: "INCOMPLETE_STAGES", message: `Незавершённых этапов: ${stages?.incomplete}.` });
  if (Number(tasks?.active ?? 0)) blockers.push({ code: "ACTIVE_TASKS", message: `Незавершённых задач: ${tasks?.active}.` });
  if (Number(additional?.active ?? 0)) blockers.push({ code: "ACTIVE_ADDITIONAL_WORKS", message: `Дополнительных работ в активном согласовании: ${additional?.active}.` });
  if (Number(additional?.approved_without_tasks ?? 0)) warnings.push({ code: "ADDITIONAL_WORKS_WITHOUT_TASKS", message: "Есть согласованные допработы без производственных задач." });
  if (Number(hidden?.missing ?? 0)) warnings.push({ code: "HIDDEN_WORK_PHOTOS", message: `Не хватает фото скрытых работ: ${hidden?.missing}.` });
  if (!project.published_forecast_end_date) warnings.push({ code: "NO_PUBLISHED_FORECAST", message: "Клиенту не опубликован прогноз сдачи." });
  if (Number(obligations?.open ?? 0)) warnings.push({ code: "OPEN_OBLIGATIONS", message: `Открытых обязательств: ${obligations?.open}.` });
  if (Number(claims?.pending ?? 0)) warnings.push({ code: "PENDING_PAYMENT_CLAIMS", message: `Заявлений об оплате на проверке: ${claims?.pending}.` });
  return { ready: blockers.length === 0, blockers, warnings, checkedAt: now() };
}

async function serializeEmployee(actor: AuthUser, projectId: string) {
  const handover = await handoverRow(projectId), readiness = await getHandoverReadiness(actor, projectId);
  if (!handover) return { handover: null, readiness, rounds: [], defects: [], events: [], capabilities: await capabilities(actor) };
  const [rounds, defects, events, defectEvents, links, files, employees] = await Promise.all([
    query<Record<string, unknown>>("SELECT * FROM project_handover_rounds WHERE handover_id=$1 ORDER BY round_number DESC", [handover.id]),
    query<Record<string, unknown>>(`SELECT d.*,u.display_name assigned_to_name FROM project_handover_defects d LEFT JOIN users u ON u.id=d.assigned_to_user_id WHERE d.handover_id=$1 ORDER BY d.defect_number DESC`, [handover.id]),
    query<Record<string, unknown>>("SELECT e.*,COALESCE(u.display_name,pu.login_identifier) actor_name FROM project_handover_events e LEFT JOIN users u ON u.id=e.employee_user_id LEFT JOIN client_portal_users pu ON pu.id=e.client_portal_user_id WHERE e.handover_id=$1 ORDER BY e.occurred_at DESC", [handover.id]),
    query<Record<string, unknown>>("SELECT e.*,COALESCE(u.display_name,pu.login_identifier) actor_name FROM project_handover_defect_events e LEFT JOIN users u ON u.id=e.employee_user_id LEFT JOIN client_portal_users pu ON pu.id=e.client_portal_user_id WHERE e.handover_id=$1 ORDER BY e.occurred_at DESC", [handover.id]),
    query<Record<string, unknown>>("SELECT l.*,t.title task_title,t.status task_status FROM handover_defect_task_links l JOIN tasks t ON t.id=l.task_id JOIN project_handover_defects d ON d.id=l.defect_id WHERE d.handover_id=$1", [handover.id]),
    query<Record<string, unknown>>("SELECT id,handover_round_id,handover_defect_id,original_filename,category,visibility,created_at FROM attachments WHERE handover_id=$1 AND upload_status='LINKED' AND deleted_at IS NULL ORDER BY created_at DESC", [handover.id]),
    query<Record<string, unknown>>("SELECT id,display_name name FROM users WHERE status='ACTIVE' AND role IN('OWNER','EMPLOYEE') ORDER BY display_name", []),
  ]);
  return { handover, readiness, rounds, defects: defects.map(defect => ({ ...defect, events: defectEvents.filter(event => event.defect_id === defect.id), taskLinks: links.filter(link => link.defect_id === defect.id), files: files.filter(file => file.handover_defect_id === defect.id) })), events, files: files.filter(file => !file.handover_defect_id), employees, capabilities: await capabilities(actor) };
}
async function capabilities(actor: AuthUser) { const access = await getAccessProfile(actor); return Object.fromEntries(["prepare","sendToClient","manualAccept","cancel","viewDefects","manageDefects","assignDefects","resolveDefects","createTask","requestReinspection","uploadFiles"].map(key => [key, actor.role === "OWNER" || Boolean(access.actions[`handover.${key}` as keyof typeof access.actions])])) }
export async function getProjectHandover(actor: AuthUser, projectId: string) { await permit(actor, "handover.view", projectId); return serializeEmployee(actor, projectId); }

export async function prepareProjectHandover(actor: AuthUser, projectId: string) {
  await permit(actor, "handover.prepare", projectId); const readiness = await getHandoverReadiness(actor, projectId); if (!readiness.ready) throw new HandoverError("Объект пока нельзя передать на финальную сдачу.", 409, { blockers: readiness.blockers });
  const timestamp = now(), handoverId = id(), roundId = id();
  await transaction([
    { text: "SELECT pg_advisory_xact_lock(hashtext($1))", params: [`handover:${projectId}`] },
    { text: `INSERT INTO project_handovers(id,project_id,status,current_round_id,prepared_at,prepared_by_user_id,created_at,updated_at) VALUES($1,$2,'READY_FOR_HANDOVER',$3,$4,$5,$4,$4) ON CONFLICT(project_id) DO UPDATE SET status='READY_FOR_HANDOVER',prepared_at=excluded.prepared_at,prepared_by_user_id=excluded.prepared_by_user_id,updated_at=excluded.updated_at WHERE project_handovers.status='NOT_READY'`, params: [handoverId, projectId, roundId, timestamp, actor.id] },
    { text: `INSERT INTO project_handover_rounds(id,handover_id,project_id,round_number,status,opened_at,opened_by_user_id,created_at,updated_at) SELECT $1,h.id,h.project_id,1,'OPEN',$2,$3,$2,$2 FROM project_handovers h WHERE h.project_id=$4 AND NOT EXISTS(SELECT 1 FROM project_handover_rounds r WHERE r.handover_id=h.id)`, params: [roundId, timestamp, actor.id, projectId] },
    { text: "UPDATE project_handovers h SET current_round_id=(SELECT id FROM project_handover_rounds WHERE handover_id=h.id ORDER BY round_number DESC LIMIT 1) WHERE project_id=$1 AND current_round_id IS NULL", params: [projectId] },
    { text: "INSERT INTO project_handover_events(id,handover_id,project_id,round_id,type,employee_user_id,metadata_json,occurred_at) SELECT $1,h.id,h.project_id,h.current_round_id,'PREPARED',$2,$3::jsonb,$4 FROM project_handovers h WHERE h.project_id=$5", params: [id(), actor.id, JSON.stringify({ warnings: readiness.warnings.map(item => item.code) }), timestamp, projectId] },
    employeeAudit(actor, "HANDOVER_PREPARED", projectId, { warnings: readiness.warnings.map(item => item.code) }, timestamp),
  ]);
  return serializeEmployee(actor, projectId);
}

export async function sendProjectHandover(actor: AuthUser, projectId: string) {
  await permit(actor, "handover.sendToClient", projectId); const handover = await requireHandover(projectId), portal = await first("SELECT pu.id FROM client_portal_users pu JOIN projects p ON p.client_id=pu.client_id WHERE p.id=$1 AND pu.status='ACTIVE'", [projectId]); if (!portal) throw new HandoverError("У клиента нет активного личного кабинета.", 409);
  const timestamp = now(), result = await query(`WITH changed AS (UPDATE project_handovers SET status='AWAITING_CLIENT_INSPECTION',sent_at=$1,sent_by_user_id=$2,updated_at=$1 WHERE id=$3 AND status='READY_FOR_HANDOVER' RETURNING id) SELECT COUNT(*)::int count FROM changed`, [timestamp, actor.id, handover.id]); if (Number(result[0]?.count) !== 1) throw new HandoverError("Сдача уже передана или её состояние изменилось.", 409);
  await transaction([employeeEvent(handover, actor, "SENT_TO_CLIENT", timestamp, handover.current_round_id), employeeAudit(actor, "HANDOVER_SENT_TO_CLIENT", handover.id, { projectId }, timestamp)]); return serializeEmployee(actor, projectId);
}

export async function manualAcceptProjectHandover(actor: AuthUser, projectId: string, input: Record<string, unknown>) {
  await permit(actor, "handover.manualAccept", projectId); const handover = await requireHandover(projectId), reason = clean(input.reason); if (!reason) throw new HandoverError("Укажите основание ручной приёмки."); const acceptedAt = Number(input.acceptedAt) || now(), open = await first<{ count: number }>(`SELECT COUNT(*)::int count FROM project_handover_defects WHERE handover_id=$1 AND status IN ${OPEN_DEFECTS}`, [handover.id]); if (Number(open?.count) && (!input.overrideOpenDefects || !clean(input.overrideReason))) throw new HandoverError("Есть незакрытые замечания. Подтвердите override и укажите причину.", 409, { openDefects: open?.count });
  const timestamp = now(), snapshot = { acceptedAt, source: "MANUAL", reason, openDefects: Number(open?.count), overrideReason: clean(input.overrideReason) || null };
  const rows = await query(`WITH changed AS (UPDATE project_handovers SET status='ACCEPTED',accepted_at=$1,manually_accepted_by_user_id=$2,manual_acceptance_reason=$3,actual_handover_at=$1,warranty_starts_at=$1,final_snapshot_json=$4::jsonb,updated_at=$5 WHERE id=$6 AND status NOT IN('ACCEPTED','CANCELLED') RETURNING id) SELECT COUNT(*)::int count FROM changed`, [acceptedAt, actor.id, reason, JSON.stringify(snapshot), timestamp, handover.id]); if (Number(rows[0]?.count) !== 1) throw new HandoverError("Сдача уже завершена или отменена.", 409);
  await transaction([employeeEvent(handover, actor, "MANUALLY_ACCEPTED", timestamp, handover.current_round_id, reason, snapshot), employeeAudit(actor, "HANDOVER_MANUALLY_ACCEPTED", handover.id, { projectId, ...snapshot }, timestamp)]); return serializeEmployee(actor, projectId);
}

export async function cancelProjectHandover(actor: AuthUser, projectId: string, reasonValue: unknown) { await permit(actor, "handover.cancel", projectId); const handover = await requireHandover(projectId), reason = clean(reasonValue); if (!reason) throw new HandoverError("Укажите причину отмены."); const timestamp = now(); const rows = await query("WITH changed AS (UPDATE project_handovers SET status='CANCELLED',cancelled_at=$1,cancelled_by_user_id=$2,cancellation_reason=$3,updated_at=$1 WHERE id=$4 AND status<>'ACCEPTED' AND status<>'CANCELLED' RETURNING id) SELECT COUNT(*)::int count FROM changed", [timestamp, actor.id, reason, handover.id]); if (Number(rows[0]?.count) !== 1) throw new HandoverError("Принятую или уже отменённую сдачу отменить нельзя.", 409); await transaction([employeeEvent(handover, actor, "CANCELLED", timestamp, handover.current_round_id, reason), employeeAudit(actor, "HANDOVER_CANCELLED", handover.id, { projectId, reason }, timestamp)]); return serializeEmployee(actor, projectId); }

async function employeeDefect(actor: AuthUser, defectId: string, permission: Parameters<typeof permit>[1]) { const defect = await first<{ id: string; handover_id: string; project_id: string; round_id: string; status: string }>("SELECT id,handover_id,project_id,round_id,status FROM project_handover_defects WHERE id=$1", [defectId]); if (!defect) throw new HandoverError("Замечание не найдено.", 404); await permit(actor, permission, defect.project_id); return defect; }
export async function createEmployeeHandoverDefect(actor: AuthUser, projectId: string, input: Record<string, unknown>) { await permit(actor, "handover.manageDefects", projectId); const handover = await requireHandover(projectId), title = clean(input.title, 200), description = clean(input.description); if (!title || !description) throw new HandoverError("Заполните название и описание замечания."); if (!handover.current_round_id) throw new HandoverError("Раунд осмотра недоступен.", 409); const timestamp = now(), defectId = id(); try { await transaction([{ text: "SELECT pg_advisory_xact_lock(hashtext($1))", params: [`handover-defect:${projectId}`] }, { text: `INSERT INTO project_handover_defects(id,handover_id,round_id,project_id,defect_number,title,description,location,priority,status,created_by_user_id,assigned_to_user_id,internal_comment,created_at,updated_at) SELECT $1,h.id,r.id,h.project_id,COALESCE((SELECT MAX(defect_number)+1 FROM project_handover_defects WHERE project_id=h.project_id),1),$2,$3,$4,$5,'OPEN',$6,$7,$8,$9,$9 FROM project_handovers h JOIN project_handover_rounds r ON r.id=h.current_round_id WHERE h.id=$10 AND h.status NOT IN('ACCEPTED','CANCELLED') AND r.status='OPEN'`, params: [defectId, title, description, clean(input.location, 300) || null, input.priority === "IMPORTANT" ? "IMPORTANT" : "NORMAL", actor.id, clean(input.assignedToUserId, 100) || null, clean(input.internalComment) || null, timestamp, handover.id] }, defectEvent({ id: defectId, handover_id: handover.id, project_id: projectId }, "CREATED_BY_EMPLOYEE", timestamp, { employee: actor.id }), employeeAudit(actor, "HANDOVER_DEFECT_CREATED", defectId, { projectId }, timestamp)]); } catch { throw new HandoverError("Открытый раунд осмотра недоступен.", 409); } return serializeEmployee(actor, projectId); }
export async function mutateHandoverDefect(actor: AuthUser, defectId: string, input: Record<string, unknown>) {
  const action = clean(input.action, 40) || "UPDATE", permission = action === "ASSIGN" ? "handover.assignDefects" : action === "RESOLVE" ? "handover.resolveDefects" : action === "CREATE_TASK" ? "handover.createTask" : "handover.manageDefects"; const defect = await employeeDefect(actor, defectId, permission), timestamp = now(); let event = action;
  if (action === "UPDATE") { const title = clean(input.title, 200), description = clean(input.description); if (!title || !description) throw new HandoverError("Заполните название и описание."); await query("UPDATE project_handover_defects SET title=$1,description=$2,location=$3,priority=$4,internal_comment=$5,updated_at=$6 WHERE id=$7 AND status IN('OPEN','IN_PROGRESS','DISPUTED')", [title, description, clean(input.location, 300) || null, input.priority === "IMPORTANT" ? "IMPORTANT" : "NORMAL", clean(input.internalComment) || null, timestamp, defectId]); }
  else if (action === "ASSIGN") { const assignee = clean(input.assignedToUserId, 100); if (assignee && !(await first("SELECT id FROM users WHERE id=$1 AND status='ACTIVE'", [assignee]))) throw new HandoverError("Исполнитель недоступен."); await query("UPDATE project_handover_defects SET assigned_to_user_id=$1,status=CASE WHEN status='OPEN' AND $1::text IS NOT NULL THEN 'IN_PROGRESS' ELSE status END,updated_at=$2 WHERE id=$3 AND status NOT IN('ACCEPTED','CANCELLED')", [assignee || null, timestamp, defectId]); }
  else if (action === "RESOLVE") { const comment = clean(input.comment); if (!comment) throw new HandoverError("Комментарий об устранении обязателен."); const rows = await query("WITH changed AS (UPDATE project_handover_defects SET status='RESOLVED',resolution_comment=$1,resolved_at=$2,resolved_by_user_id=$3,updated_at=$2 WHERE id=$4 AND status IN('OPEN','IN_PROGRESS','DISPUTED') RETURNING id) SELECT COUNT(*)::int count FROM changed", [comment, timestamp, actor.id, defectId]); if (Number(rows[0]?.count) !== 1) throw new HandoverError("Замечание уже закрыто или его состояние изменилось.", 409); }
  else if (action === "REOPEN") { await query("UPDATE project_handover_defects SET status='OPEN',resolved_at=NULL,resolved_by_user_id=NULL,accepted_at=NULL,accepted_by_client_portal_user_id=NULL,updated_at=$1 WHERE id=$2 AND status IN('RESOLVED','ACCEPTED','DISPUTED')", [timestamp, defectId]); }
  else if (action === "CANCEL") { const reason = clean(input.comment); if (!reason) throw new HandoverError("Укажите причину отмены замечания."); await query("UPDATE project_handover_defects SET status='CANCELLED',cancelled_at=$1,cancelled_by_user_id=$2,updated_at=$1 WHERE id=$3 AND status NOT IN('ACCEPTED','CANCELLED')", [timestamp, actor.id, defectId]); }
  else if (action === "CREATE_TASK") { const title = clean(input.title, 200); if (!title) throw new HandoverError("Укажите название задачи."); const taskId = id(), stage = await first<{ id: string; production_plan_id: string }>("SELECT id,production_plan_id FROM project_stages WHERE project_id=$1 AND archived_at IS NULL ORDER BY sort_order DESC LIMIT 1", [defect.project_id]); if (!stage) throw new HandoverError("Для объекта нет производственного этапа.", 409); await transaction([{ text: "INSERT INTO tasks(id,title,created_by_user_id,project_id,production_plan_id,stage_id,description,position,progress_type,weight_within_stage,responsible_user_id,client_visible,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE((SELECT MAX(position)+1 FROM tasks WHERE stage_id=$6),1),'BINARY',0,$3,1,'TODO',$8,$8)", params: [taskId, title, actor.id, defect.project_id, stage.production_plan_id, stage.id, clean(input.description) || `Устранение замечания №${defectId}`, timestamp] }, { text: "INSERT INTO handover_defect_task_links(id,defect_id,task_id,created_by_user_id,created_at) VALUES($1,$2,$3,$4,$5)", params: [id(), defectId, taskId, actor.id, timestamp] }]); event = "TASK_CREATED"; }
  else throw new HandoverError("Неизвестное действие.");
  await transaction([defectEvent(defect, event, timestamp, { employee: actor.id }, action === "RESOLVE" || action === "CANCEL" ? clean(input.comment) : null), employeeAudit(actor, `HANDOVER_DEFECT_${event}`, defectId, { projectId: defect.project_id }, timestamp)]); return serializeEmployee(actor, defect.project_id);
}

export async function requestHandoverReinspection(actor: AuthUser, projectId: string) { await permit(actor, "handover.requestReinspection", projectId); const handover = await requireHandover(projectId), open = await first<{ count: number }>(`SELECT COUNT(*)::int count FROM project_handover_defects WHERE handover_id=$1 AND status IN ${OPEN_DEFECTS}`, [handover.id]); if (Number(open?.count)) throw new HandoverError("Сначала закройте все замечания.", 409); const timestamp = now(), roundId = id(); try { await transaction([{ text: "SELECT pg_advisory_xact_lock(hashtext($1))", params: [`handover-round:${handover.id}`] }, { text: "UPDATE project_handover_rounds SET status='SUPERSEDED',superseded_at=$1,updated_at=$1 WHERE handover_id=$2 AND status='OPEN'", params: [timestamp, handover.id] }, { text: "INSERT INTO project_handover_rounds(id,handover_id,project_id,round_number,status,opened_at,opened_by_user_id,created_at,updated_at) SELECT $1,$2,$3,COALESCE(MAX(round_number),0)+1,'OPEN',$4,$5,$4,$4 FROM project_handover_rounds WHERE handover_id=$2", params: [roundId, handover.id, projectId, timestamp, actor.id] }, { text: "UPDATE project_handovers SET status='REINSPECTION_REQUIRED',current_round_id=$1,updated_at=$2 WHERE id=$3 AND status IN('CORRECTIONS_REQUIRED','REINSPECTION_REQUIRED')", params: [roundId, timestamp, handover.id] }, employeeEvent(handover, actor, "REINSPECTION_REQUESTED", timestamp, roundId), employeeAudit(actor, "HANDOVER_REINSPECTION_REQUESTED", handover.id, { projectId, roundId }, timestamp)]); } catch { throw new HandoverError("Повторный осмотр уже создан.", 409); } return serializeEmployee(actor, projectId); }

function clientDto(handover: HandoverRow, round: Record<string, unknown> | null, defects: Record<string, unknown>[], files: Record<string, unknown>[]) { return { id: handover.id, projectId: handover.project_id, status: handover.status, acceptedAt: handover.accepted_at, project: { name: handover.project_name, address: handover.address, apartment: handover.apartment }, round: round ? { id: round.id, number: round.round_number, status: round.status, openedAt: round.opened_at, submittedAt: round.submitted_at } : null, defects: defects.map(item => ({ id: item.id, number: item.defect_number, title: item.title, description: item.description, location: item.location, priority: item.priority, status: item.status, resolutionComment: item.resolution_comment, disputeComment: item.dispute_comment, createdAt: item.created_at, files: files.filter(file => file.handover_defect_id === item.id).map(file => ({ id: file.id, filename: file.original_filename, category: file.category, url: `/api/client/files/${file.id}` })) })), files: files.filter(file => !file.handover_defect_id).map(file => ({ id: file.id, filename: file.original_filename, category: file.category, url: `/api/client/files/${file.id}` })) }; }
export async function getClientProjectHandover(user: ClientPortalUser, projectId: string) { const handover = await clientHandover(user, projectId); if (!["AWAITING_CLIENT_INSPECTION","CORRECTIONS_REQUIRED","REINSPECTION_REQUIRED","ACCEPTED"].includes(handover.status)) throw new HandoverError("Сдача ещё не передана клиенту.", 404); const [round, defects, files] = await Promise.all([first<Record<string, unknown>>("SELECT * FROM project_handover_rounds WHERE id=$1 AND handover_id=$2", [handover.current_round_id, handover.id]), query<Record<string, unknown>>("SELECT id,defect_number,title,description,location,priority,status,resolution_comment,dispute_comment,created_at FROM project_handover_defects WHERE handover_id=$1 AND status<>'CANCELLED' ORDER BY defect_number", [handover.id]), query<Record<string, unknown>>("SELECT id,handover_defect_id,original_filename,category FROM attachments WHERE handover_id=$1 AND upload_status='LINKED' AND deleted_at IS NULL AND (visibility='CLIENT' OR client_visible=1) ORDER BY created_at", [handover.id])]); return clientDto(handover, round, defects, files); }

export async function createClientHandoverDefect(user: ClientPortalUser, projectId: string, input: Record<string, unknown>) { const handover = await clientHandover(user, projectId), title = clean(input.title, 200), description = clean(input.description); if (!title || !description) throw new HandoverError("Заполните название и описание замечания."); if (!handover.current_round_id) throw new HandoverError("Раунд осмотра недоступен.", 409); const timestamp = now(), defectId = id(); try { await transaction([{ text: "SELECT pg_advisory_xact_lock(hashtext($1))", params: [`handover-defect:${projectId}`] }, { text: `INSERT INTO project_handover_defects(id,handover_id,round_id,project_id,defect_number,title,description,location,priority,status,created_by_client_portal_user_id,created_at,updated_at) SELECT $1,h.id,r.id,h.project_id,COALESCE((SELECT MAX(defect_number)+1 FROM project_handover_defects WHERE project_id=h.project_id),1),$2,$3,$4,$5,'OPEN',$6,$7,$7 FROM project_handovers h JOIN project_handover_rounds r ON r.id=h.current_round_id WHERE h.id=$8 AND h.status IN('AWAITING_CLIENT_INSPECTION','REINSPECTION_REQUIRED') AND r.status='OPEN'`, params: [defectId, title, description, clean(input.location, 300) || null, input.priority === "IMPORTANT" ? "IMPORTANT" : "NORMAL", user.id, timestamp, handover.id] }, defectEvent({ id: defectId, handover_id: handover.id, project_id: projectId }, "CREATED_BY_CLIENT", timestamp, { client: user.id })]); } catch { throw new HandoverError("Раунд осмотра уже закрыт.", 409); } return getClientProjectHandover(user, projectId); }

export async function mutateClientHandover(user: ClientPortalUser, projectId: string, input: Record<string, unknown>) { const handover = await clientHandover(user, projectId), action = clean(input.action, 40), timestamp = now();
  if (action === "UPDATE_DEFECT" || action === "DELETE_DEFECT") { const defectId = clean(input.defectId, 100), defect = await first<{ id: string; handover_id: string; project_id: string }>("SELECT d.id,d.handover_id,d.project_id FROM project_handover_defects d JOIN project_handover_rounds r ON r.id=d.round_id WHERE d.id=$1 AND d.handover_id=$2 AND d.created_by_client_portal_user_id=$3 AND d.status='OPEN' AND r.status='OPEN'", [defectId, handover.id, user.id]); if (!defect) throw new HandoverError("Черновик замечания недоступен.", 409); if (action === "DELETE_DEFECT") { await query("UPDATE project_handover_defects SET status='CANCELLED',cancelled_at=$1,updated_at=$1 WHERE id=$2", [timestamp, defectId]); const event = defectEvent(defect, "DRAFT_DELETED", timestamp, { client: user.id }); await query(event.text, event.params); } else { const title = clean(input.title, 200), description = clean(input.description); if (!title || !description) throw new HandoverError("Заполните название и описание."); await query("UPDATE project_handover_defects SET title=$1,description=$2,location=$3,priority=$4,updated_at=$5 WHERE id=$6", [title, description, clean(input.location, 300) || null, input.priority === "IMPORTANT" ? "IMPORTANT" : "NORMAL", timestamp, defectId]); } return getClientProjectHandover(user, projectId); }
  if (action === "SUBMIT_DEFECTS") { const comment = clean(input.comment), rows = await query(`WITH locked AS (SELECT h.id,h.current_round_id FROM project_handovers h JOIN project_handover_rounds r ON r.id=h.current_round_id WHERE h.id=$1 AND h.status IN('AWAITING_CLIENT_INSPECTION','REINSPECTION_REQUIRED') AND r.status='OPEN' AND EXISTS(SELECT 1 FROM project_handover_defects d WHERE d.round_id=r.id AND d.status<>'CANCELLED') FOR UPDATE OF h,r), changed_round AS (UPDATE project_handover_rounds r SET status='SUBMITTED_WITH_DEFECTS',submitted_at=$2,submitted_by_client_portal_user_id=$3,client_comment=$4,updated_at=$2 FROM locked WHERE r.id=locked.current_round_id RETURNING r.id), changed_handover AS (UPDATE project_handovers h SET status='CORRECTIONS_REQUIRED',updated_at=$2 FROM locked WHERE h.id=locked.id AND EXISTS(SELECT 1 FROM changed_round) RETURNING h.id) SELECT COUNT(*)::int count FROM changed_handover`, [handover.id, timestamp, user.id, comment || null]); if (Number(rows[0]?.count) !== 1) throw new HandoverError("Раунд уже закрыт или замечания отсутствуют.", 409); await transaction([clientEvent(handover, user, "DEFECTS_SUBMITTED", timestamp, handover.current_round_id, comment || null), { text: "INSERT INTO client_portal_audit_events(id,action,entity_type,entity_id,client_id,client_portal_user_id,metadata_json,occurred_at) VALUES($1,'HANDOVER_DEFECTS_SUBMITTED','ProjectHandover',$2,$3,$4,$5::jsonb,$6)", params: [id(), handover.id, user.clientId, user.id, JSON.stringify({ projectId }), timestamp] }]); return getClientProjectHandover(user, projectId); }
  if (action === "ACCEPT_DEFECT" || action === "DISPUTE_DEFECT") { const defectId = clean(input.defectId, 100), comment = clean(input.comment), target = action === "ACCEPT_DEFECT" ? "ACCEPTED" : "DISPUTED"; if (target === "DISPUTED" && !comment) throw new HandoverError("Укажите, что осталось исправить."); const defect = await first<{ id: string; handover_id: string; project_id: string }>("SELECT id,handover_id,project_id FROM project_handover_defects WHERE id=$1 AND handover_id=$2 AND status='RESOLVED'", [defectId, handover.id]); if (!defect) throw new HandoverError("Решение по замечанию уже сохранено.", 409); await query(`UPDATE project_handover_defects SET status=$1,accepted_at=CASE WHEN $1='ACCEPTED' THEN $2 ELSE NULL END,accepted_by_client_portal_user_id=CASE WHEN $1='ACCEPTED' THEN $3 ELSE NULL END,disputed_at=CASE WHEN $1='DISPUTED' THEN $2 ELSE NULL END,dispute_comment=CASE WHEN $1='DISPUTED' THEN $4 ELSE NULL END,updated_at=$2 WHERE id=$5 AND status='RESOLVED'`, [target, timestamp, user.id, comment || null, defectId]); await transaction([defectEvent(defect, target, timestamp, { client: user.id }, comment || null)]); return getClientProjectHandover(user, projectId); }
  if (action === "FINAL_ACCEPT") { const open = await first<{ count: number }>(`SELECT COUNT(*)::int count FROM project_handover_defects WHERE handover_id=$1 AND status IN ${OPEN_DEFECTS}`, [handover.id]); if (Number(open?.count)) throw new HandoverError("Сначала примите все устранённые замечания.", 409, { openDefects: open?.count }); const snapshot = { source: "CLIENT_PORTAL", acceptedAt: timestamp, projectId, defectCount: await first("SELECT COUNT(*)::int count FROM project_handover_defects WHERE handover_id=$1 AND status<>'CANCELLED'", [handover.id]) }; const rows = await query(`WITH locked AS (SELECT h.id,h.current_round_id FROM project_handovers h JOIN project_handover_rounds r ON r.id=h.current_round_id WHERE h.id=$1 AND h.status IN('AWAITING_CLIENT_INSPECTION','REINSPECTION_REQUIRED','CORRECTIONS_REQUIRED') AND r.status='OPEN' FOR UPDATE OF h,r), changed_round AS (UPDATE project_handover_rounds r SET status='ACCEPTED',accepted_at=$2,accepted_by_client_portal_user_id=$3,updated_at=$2 FROM locked WHERE r.id=locked.current_round_id RETURNING r.id), changed_handover AS (UPDATE project_handovers h SET status='ACCEPTED',accepted_at=$2,accepted_by_client_portal_user_id=$3,actual_handover_at=$2,warranty_starts_at=$2,final_snapshot_json=$4::jsonb,updated_at=$2 FROM locked WHERE h.id=locked.id AND EXISTS(SELECT 1 FROM changed_round) RETURNING h.id) SELECT COUNT(*)::int count FROM changed_handover`, [handover.id, timestamp, user.id, JSON.stringify(snapshot)]); if (Number(rows[0]?.count) !== 1) throw new HandoverError("Сдача уже принята или состояние изменилось.", 409); await transaction([clientEvent(handover, user, "ACCEPTED", timestamp, handover.current_round_id), { text: "INSERT INTO client_portal_audit_events(id,action,entity_type,entity_id,client_id,client_portal_user_id,metadata_json,occurred_at) VALUES($1,'HANDOVER_ACCEPTED','ProjectHandover',$2,$3,$4,$5::jsonb,$6)", params: [id(), handover.id, user.clientId, user.id, JSON.stringify({ projectId }), timestamp] }]); return getClientProjectHandover(user, projectId); }
  throw new HandoverError("Неизвестное действие.");
}
