import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: integer("created_at", { mode: "timestamp" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull() };

export const users = sqliteTable("users", { id:text("id").primaryKey(), authProvider:text("auth_provider",{enum:["LOCAL","SUPABASE","EXTERNAL"]}).notNull().default("LOCAL"), externalAuthId:text("external_auth_id"), email:text("email"), username:text("username").notNull(), usernameNormalized:text("username_normalized").notNull(), displayName:text("display_name").notNull(), role:text("role",{enum:["OWNER","EMPLOYEE","CLIENT"]}).notNull(), employeeId:text("employee_id"), clientId:text("client_id"), status:text("status",{enum:["ACTIVE","BLOCKED"]}).notNull().default("ACTIVE"), isProtectedOwner:integer("is_protected_owner",{mode:"boolean"}).notNull().default(false), passwordHash:text("password_hash"), passwordSalt:text("password_salt"), passwordIterations:integer("password_iterations"), passwordChangedAt:integer("password_changed_at",{mode:"timestamp"}), lastLoginAt:integer("last_login_at",{mode:"timestamp"}), ...timestamps }, t=>[uniqueIndex("idx_users_username_normalized").on(t.usernameNormalized),uniqueIndex("idx_users_external_auth_id").on(t.externalAuthId),index("idx_users_employee").on(t.employeeId),index("idx_users_role_status").on(t.role,t.status)]);

export const employees = sqliteTable("employees", { id:text("id").primaryKey(), fullName:text("full_name").notNull(), phone:text("phone"), position:text("position"), contactsJson:text("contacts_json"), status:text("status").notNull().default("ACTIVE"), permissionsJson:text("permissions_json"), ...timestamps }, t=>[index("idx_employees_status").on(t.status)]);
export const authSessions = sqliteTable("auth_sessions", { id:text("id").primaryKey(), userId:text("user_id").notNull(), tokenHash:text("token_hash").notNull(), createdAt:integer("created_at",{mode:"timestamp"}).notNull(), lastSeenAt:integer("last_seen_at",{mode:"timestamp"}).notNull(), expiresAt:integer("expires_at",{mode:"timestamp"}).notNull(), revokedAt:integer("revoked_at",{mode:"timestamp"}), userAgent:text("user_agent") }, t=>[uniqueIndex("idx_auth_sessions_token_hash").on(t.tokenHash),index("idx_auth_sessions_user_expires").on(t.userId,t.expiresAt)]);
export const authAttempts = sqliteTable("auth_attempts", { id:text("id").primaryKey(), identifierHash:text("identifier_hash").notNull(), attemptedAt:integer("attempted_at",{mode:"timestamp"}).notNull(), succeeded:integer("succeeded",{mode:"boolean"}).notNull() }, t=>[index("idx_auth_attempts_identifier_time").on(t.identifierHash,t.attemptedAt)]);
export const userPermissions = sqliteTable("user_permissions", { id:text("id").primaryKey(), userId:text("user_id").notNull(), permission:text("permission").notNull(), scope:text("scope").notNull().default("COMPANY"), allowed:integer("allowed",{mode:"boolean"}).notNull().default(true), ...timestamps }, t=>[uniqueIndex("idx_user_permission_scope").on(t.userId,t.permission,t.scope)]);
export const userProjectAccess = sqliteTable("user_project_access", { id:text("id").primaryKey(), userId:text("user_id").notNull(), projectId:text("project_id").notNull(), accessLevel:text("access_level").notNull(), ...timestamps }, t=>[uniqueIndex("idx_user_project_access").on(t.userId,t.projectId)]);
export const auditLogs = sqliteTable("audit_logs", { id:text("id").primaryKey(), actorUserId:text("actor_user_id").notNull(), action:text("action").notNull(), entityType:text("entity_type").notNull(), entityId:text("entity_id").notNull(), occurredAt:integer("occurred_at",{mode:"timestamp"}).notNull(), metadataJson:text("metadata_json").notNull().default("{}") }, t=>[index("idx_audit_actor_time").on(t.actorUserId,t.occurredAt),index("idx_audit_entity_time").on(t.entityType,t.entityId,t.occurredAt)]);
export const clients = sqliteTable("clients", { id:text("id").primaryKey(), name:text("name").notNull(), phone:text("phone"), contactsJson:text("contacts_json"), source:text("source"), comment:text("comment"), ownerEmployeeId:text("owner_employee_id"), status:text("status").notNull(), ...timestamps }, t=>[index("idx_clients_phone").on(t.phone),index("idx_clients_owner").on(t.ownerEmployeeId)]);
export const leads = sqliteTable("leads", { id:text("id").primaryKey(), clientId:text("client_id").notNull(), source:text("source").notNull(), ownerEmployeeId:text("owner_employee_id"), status:text("status").notNull(), notes:text("notes"), nextAction:text("next_action"), nextContactAt:integer("next_contact_at",{mode:"timestamp"}), ...timestamps }, t=>[index("idx_leads_status_next_contact").on(t.status,t.nextContactAt),index("idx_leads_client").on(t.clientId)]);
export const orders = sqliteTable("orders", { id:text("id").primaryKey(), number:text("number").notNull(), clientId:text("client_id").notNull(), type:text("type",{enum:["ACCEPTANCE","RENOVATION"]}).notNull(), title:text("title").notNull(), amountKopecks:integer("amount_kopecks").notNull(), status:text("status").notNull(), ...timestamps }, t=>[uniqueIndex("idx_orders_number").on(t.number),index("idx_orders_client").on(t.clientId)]);
export const projects = sqliteTable("projects", { id:text("id").primaryKey(), orderId:text("order_id").notNull(), clientId:text("client_id").notNull(), name:text("name").notNull(), residentialComplex:text("residential_complex"), address:text("address"), apartment:text("apartment"), managerEmployeeId:text("manager_employee_id"), foremanEmployeeId:text("foreman_employee_id"), status:text("status").notNull(), startDate:integer("start_date",{mode:"timestamp"}), plannedEndDate:integer("planned_end_date",{mode:"timestamp"}), forecastEndDate:integer("forecast_end_date",{mode:"timestamp"}), actualEndDate:integer("actual_end_date",{mode:"timestamp"}), contractAmountKopecks:integer("contract_amount_kopecks").notNull(), comment:text("comment"), ...timestamps }, t=>[index("idx_projects_status_manager").on(t.status,t.managerEmployeeId),index("idx_projects_client").on(t.clientId)]);
export const cashboxes = sqliteTable("cashboxes", { id:text("id").primaryKey(), name:text("name").notNull(), type:text("type").notNull(), ownerEmployeeId:text("owner_employee_id"), currency:text("currency").notNull().default("RUB"), isActive:integer("is_active",{mode:"boolean"}).notNull().default(true), ...timestamps });
export const financialTransactions = sqliteTable("financial_transactions", { id:text("id").primaryKey(), amountKopecks:integer("amount_kopecks").notNull(), transactionDate:integer("transaction_date",{mode:"timestamp"}).notNull(), type:text("type",{enum:["INCOME","EXPENSE","TRANSFER","REFUND","OWNER_PAYOUT"]}).notNull(), authorUserId:text("author_user_id").notNull(), cashboxId:text("cashbox_id").notNull(), destinationCashboxId:text("destination_cashbox_id"), clientId:text("client_id"), projectId:text("project_id"), orderId:text("order_id"), category:text("category").notNull(), subcategory:text("subcategory"), purpose:text("purpose",{enum:["MATERIALS","WORKS","ADDITIONAL_WORKS","OTHER"]}), title:text("title").notNull(), comment:text("comment"), showToClient:integer("show_to_client",{mode:"boolean"}).notNull().default(false), ...timestamps }, t=>[index("idx_transactions_cashbox_date").on(t.cashboxId,t.transactionDate),index("idx_transactions_project_date").on(t.projectId,t.transactionDate),index("idx_transactions_client_purpose").on(t.clientId,t.purpose)]);
export const transactionAllocations = sqliteTable("transaction_allocations", { id:text("id").primaryKey(), transactionId:text("transaction_id").notNull(), projectId:text("project_id").notNull(), orderId:text("order_id"), amountKopecks:integer("amount_kopecks").notNull(), purpose:text("purpose").notNull(), ...timestamps }, t=>[index("idx_allocations_transaction").on(t.transactionId),index("idx_allocations_project").on(t.projectId)]);
export const attachments = sqliteTable("attachments", { id:text("id").primaryKey(), transactionId:text("transaction_id"), projectId:text("project_id"), storageKey:text("storage_key").notNull(), fileName:text("file_name").notNull(), mimeType:text("mime_type").notNull(), sizeBytes:integer("size_bytes").notNull(), kind:text("kind").notNull(), ...timestamps }, t=>[index("idx_attachments_transaction").on(t.transactionId),index("idx_attachments_project").on(t.projectId)]);
export const projectStages = sqliteTable("project_stages", { id:text("id").primaryKey(), projectId:text("project_id").notNull(), name:text("name").notNull(), plannedStart:integer("planned_start",{mode:"timestamp"}), plannedEnd:integer("planned_end",{mode:"timestamp"}), actualStart:integer("actual_start",{mode:"timestamp"}), actualEnd:integer("actual_end",{mode:"timestamp"}), status:text("status").notNull(), responsibleEmployeeId:text("responsible_employee_id"), sortOrder:integer("sort_order").notNull(), ...timestamps }, t=>[index("idx_stages_project_order").on(t.projectId,t.sortOrder)]);
export const projectDelays = sqliteTable("project_delays", { id:text("id").primaryKey(), projectId:text("project_id").notNull(), stageId:text("stage_id"), reason:text("reason").notNull(), startDate:integer("start_date",{mode:"timestamp"}).notNull(), endDate:integer("end_date",{mode:"timestamp"}), days:integer("days").notNull(), comment:text("comment"), ...timestamps }, t=>[index("idx_delays_project_start").on(t.projectId,t.startDate)]);
export const tasks = sqliteTable("tasks", { id:text("id").primaryKey(), title:text("title").notNull(), createdByUserId:text("created_by_user_id"), assigneeEmployeeId:text("assignee_employee_id"), projectId:text("project_id"), clientId:text("client_id"), leadId:text("lead_id"), deadline:integer("deadline",{mode:"timestamp"}), status:text("status").notNull(), comment:text("comment"), ...timestamps }, t=>[index("idx_tasks_assignee_status_deadline").on(t.assigneeEmployeeId,t.status,t.deadline),index("idx_tasks_project").on(t.projectId),index("idx_tasks_creator").on(t.createdByUserId)]);
export const contractors = sqliteTable("contractors", { id:text("id").primaryKey(), name:text("name").notNull(), type:text("type").notNull(), specialization:text("specialization").notNull(), phone:text("phone"), contactsJson:text("contacts_json"), comment:text("comment"), status:text("status").notNull(), ...timestamps }, t=>[index("idx_contractors_specialization_status").on(t.specialization,t.status)]);
export const contractorAgreements = sqliteTable("contractor_agreements", { id:text("id").primaryKey(), projectId:text("project_id").notNull(), contractorId:text("contractor_id").notNull(), workTitle:text("work_title").notNull(), agreedAmountKopecks:integer("agreed_amount_kopecks").notNull(), status:text("status").notNull(), ...timestamps }, t=>[index("idx_agreements_project_contractor").on(t.projectId,t.contractorId)]);
export const estimateVersions = sqliteTable("estimate_versions", { id:text("id").primaryKey(), projectId:text("project_id").notNull(), version:integer("version").notNull(), totalKopecks:integer("total_kopecks").notNull(), changeReason:text("change_reason"), createdByUserId:text("created_by_user_id").notNull(), ...timestamps }, t=>[uniqueIndex("idx_estimate_project_version").on(t.projectId,t.version)]);
export const additionalWorkVersions = sqliteTable("additional_work_versions", { id:text("id").primaryKey(), additionalWorkId:text("additional_work_id").notNull(), projectId:text("project_id").notNull(), version:integer("version").notNull(), title:text("title").notNull(), amountKopecks:integer("amount_kopecks").notNull(), scheduleDeltaDays:integer("schedule_delta_days").notNull().default(0), status:text("status").notNull(), approvedByClientId:text("approved_by_client_id"), approvedByUserId:text("approved_by_user_id"), approvedAt:integer("approved_at",{mode:"timestamp"}), ...timestamps }, t=>[uniqueIndex("idx_additional_work_version").on(t.additionalWorkId,t.version),index("idx_additional_work_project").on(t.projectId)]);
export const dailyReports = sqliteTable("daily_reports", { id:text("id").primaryKey(), projectId:text("project_id").notNull(), reportDate:integer("report_date",{mode:"timestamp"}).notNull(), authorEmployeeId:text("author_employee_id").notNull(), createdByUserId:text("created_by_user_id"), workersJson:text("workers_json"), workCompleted:text("work_completed").notNull(), comment:text("comment"), ...timestamps }, t=>[uniqueIndex("idx_daily_report_project_date").on(t.projectId,t.reportDate),index("idx_daily_report_creator").on(t.createdByUserId)]);
export const obligations = sqliteTable("obligations", { id:text("id").primaryKey(), direction:text("direction").notNull(), counterpartyType:text("counterparty_type").notNull(), counterpartyId:text("counterparty_id").notNull(), projectId:text("project_id"), amountKopecks:integer("amount_kopecks").notNull(), paidKopecks:integer("paid_kopecks").notNull().default(0), dueDate:integer("due_date",{mode:"timestamp"}), status:text("status").notNull(), ...timestamps }, t=>[index("idx_obligations_status_due").on(t.status,t.dueDate),index("idx_obligations_counterparty").on(t.counterpartyType,t.counterpartyId)]);
